# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addCustomerUI.ui'
#
# Created: Sat Oct 13 09:42:18 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_addCustomer(object):
    def setupUi(self, addCustomer):
        addCustomer.setObjectName("addCustomer")
        addCustomer.resize(1602, 689)
        self.gridLayout_3 = QtGui.QGridLayout(addCustomer)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget = Header(addCustomer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 100))
        self.widget.setObjectName("widget")
        self.gridLayout_3.addWidget(self.widget, 0, 0, 1, 2)
        self.inputGroupBox = QtGui.QGroupBox(addCustomer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputGroupBox.sizePolicy().hasHeightForWidth())
        self.inputGroupBox.setSizePolicy(sizePolicy)
        self.inputGroupBox.setCheckable(True)
        self.inputGroupBox.setObjectName("inputGroupBox")
        self.gridLayout = QtGui.QGridLayout(self.inputGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.customerCodeLabel = QtGui.QLabel(self.inputGroupBox)
        self.customerCodeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.customerCodeLabel.setObjectName("customerCodeLabel")
        self.horizontalLayout.addWidget(self.customerCodeLabel)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.customerCodeValue = QtGui.QLineEdit(self.inputGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customerCodeValue.sizePolicy().hasHeightForWidth())
        self.customerCodeValue.setSizePolicy(sizePolicy)
        self.customerCodeValue.setMinimumSize(QtCore.QSize(200, 35))
        self.customerCodeValue.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.customerCodeValue.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.customerCodeValue.setObjectName("customerCodeValue")
        self.verticalLayout.addWidget(self.customerCodeValue)
        self.codeMandLabel = QtGui.QLabel(self.inputGroupBox)
        self.codeMandLabel.setStyleSheet("QLabel { color : red; }")
        self.codeMandLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.codeMandLabel.setObjectName("codeMandLabel")
        self.verticalLayout.addWidget(self.codeMandLabel)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.customerNameLabel = QtGui.QLabel(self.inputGroupBox)
        self.customerNameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.customerNameLabel.setObjectName("customerNameLabel")
        self.horizontalLayout_2.addWidget(self.customerNameLabel)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.customerNameValue = QtGui.QLineEdit(self.inputGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customerNameValue.sizePolicy().hasHeightForWidth())
        self.customerNameValue.setSizePolicy(sizePolicy)
        self.customerNameValue.setMinimumSize(QtCore.QSize(200, 35))
        self.customerNameValue.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.customerNameValue.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.customerNameValue.setObjectName("customerNameValue")
        self.verticalLayout_2.addWidget(self.customerNameValue)
        self.nameMandLabel = QtGui.QLabel(self.inputGroupBox)
        self.nameMandLabel.setStyleSheet("QLabel { color : red; }")
        self.nameMandLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nameMandLabel.setObjectName("nameMandLabel")
        self.verticalLayout_2.addWidget(self.nameMandLabel)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.customerAddressLabel = QtGui.QLabel(self.inputGroupBox)
        self.customerAddressLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.customerAddressLabel.setObjectName("customerAddressLabel")
        self.horizontalLayout_3.addWidget(self.customerAddressLabel)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.customerAddressValue = QtGui.QLineEdit(self.inputGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customerAddressValue.sizePolicy().hasHeightForWidth())
        self.customerAddressValue.setSizePolicy(sizePolicy)
        self.customerAddressValue.setMinimumSize(QtCore.QSize(200, 35))
        self.customerAddressValue.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.customerAddressValue.setObjectName("customerAddressValue")
        self.verticalLayout_3.addWidget(self.customerAddressValue)
        self.addressMandLabel = QtGui.QLabel(self.inputGroupBox)
        self.addressMandLabel.setStyleSheet("QLabel { color : red; }")
        self.addressMandLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.addressMandLabel.setObjectName("addressMandLabel")
        self.verticalLayout_3.addWidget(self.addressMandLabel)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gstinLabel = QtGui.QLabel(self.inputGroupBox)
        self.gstinLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.gstinLabel.setObjectName("gstinLabel")
        self.horizontalLayout_4.addWidget(self.gstinLabel)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.customerGstinValue = QtGui.QLineEdit(self.inputGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customerGstinValue.sizePolicy().hasHeightForWidth())
        self.customerGstinValue.setSizePolicy(sizePolicy)
        self.customerGstinValue.setMinimumSize(QtCore.QSize(200, 35))
        self.customerGstinValue.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.customerGstinValue.setObjectName("customerGstinValue")
        self.verticalLayout_4.addWidget(self.customerGstinValue)
        self.gstinMandLabel = QtGui.QLabel(self.inputGroupBox)
        self.gstinMandLabel.setStyleSheet("QLabel { color : red; }")
        self.gstinMandLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.gstinMandLabel.setObjectName("gstinMandLabel")
        self.verticalLayout_4.addWidget(self.gstinMandLabel)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 0, 1, 2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.stateCodeLabel = QtGui.QLabel(self.inputGroupBox)
        self.stateCodeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.stateCodeLabel.setObjectName("stateCodeLabel")
        self.horizontalLayout_5.addWidget(self.stateCodeLabel)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stateCodeValue = QtGui.QLineEdit(self.inputGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stateCodeValue.sizePolicy().hasHeightForWidth())
        self.stateCodeValue.setSizePolicy(sizePolicy)
        self.stateCodeValue.setMinimumSize(QtCore.QSize(200, 35))
        self.stateCodeValue.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.stateCodeValue.setObjectName("stateCodeValue")
        self.verticalLayout_5.addWidget(self.stateCodeValue)
        self.stateMandLabel = QtGui.QLabel(self.inputGroupBox)
        self.stateMandLabel.setStyleSheet("QLabel { color : red; }")
        self.stateMandLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.stateMandLabel.setObjectName("stateMandLabel")
        self.verticalLayout_5.addWidget(self.stateMandLabel)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.gridLayout.addLayout(self.horizontalLayout_5, 4, 0, 1, 2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.contactNoLabel = QtGui.QLabel(self.inputGroupBox)
        self.contactNoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.contactNoLabel.setObjectName("contactNoLabel")
        self.horizontalLayout_6.addWidget(self.contactNoLabel)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.contactNoValue = QtGui.QLineEdit(self.inputGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contactNoValue.sizePolicy().hasHeightForWidth())
        self.contactNoValue.setSizePolicy(sizePolicy)
        self.contactNoValue.setMinimumSize(QtCore.QSize(200, 35))
        self.contactNoValue.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.contactNoValue.setObjectName("contactNoValue")
        self.verticalLayout_6.addWidget(self.contactNoValue)
        self.contactMandLabel = QtGui.QLabel(self.inputGroupBox)
        self.contactMandLabel.setStyleSheet("QLabel { color : red; }")
        self.contactMandLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.contactMandLabel.setObjectName("contactMandLabel")
        self.verticalLayout_6.addWidget(self.contactMandLabel)
        self.horizontalLayout_6.addLayout(self.verticalLayout_6)
        self.gridLayout.addLayout(self.horizontalLayout_6, 5, 0, 1, 2)
        self.saveButton = QtGui.QPushButton(self.inputGroupBox)
        self.saveButton.setMinimumSize(QtCore.QSize(200, 35))
        self.saveButton.setObjectName("saveButton")
        self.gridLayout.addWidget(self.saveButton, 6, 0, 1, 1)
        self.discardButton = QtGui.QPushButton(self.inputGroupBox)
        self.discardButton.setMinimumSize(QtCore.QSize(200, 35))
        self.discardButton.setObjectName("discardButton")
        self.gridLayout.addWidget(self.discardButton, 6, 1, 1, 1)
        self.gridLayout_3.addWidget(self.inputGroupBox, 1, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtGui.QGroupBox(addCustomer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox.setCheckable(True)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.voucherNoLabel_2 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.voucherNoLabel_2.sizePolicy().hasHeightForWidth())
        self.voucherNoLabel_2.setSizePolicy(sizePolicy)
        self.voucherNoLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.voucherNoLabel_2.setObjectName("voucherNoLabel_2")
        self.gridLayout_4.addWidget(self.voucherNoLabel_2, 0, 0, 1, 1)
        self.searchNameValue = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchNameValue.sizePolicy().hasHeightForWidth())
        self.searchNameValue.setSizePolicy(sizePolicy)
        self.searchNameValue.setMinimumSize(QtCore.QSize(350, 35))
        self.searchNameValue.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.searchNameValue.setObjectName("searchNameValue")
        self.gridLayout_4.addWidget(self.searchNameValue, 0, 1, 1, 1)
        self.gstinLabel_2 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gstinLabel_2.sizePolicy().hasHeightForWidth())
        self.gstinLabel_2.setSizePolicy(sizePolicy)
        self.gstinLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.gstinLabel_2.setObjectName("gstinLabel_2")
        self.gridLayout_4.addWidget(self.gstinLabel_2, 0, 2, 1, 1)
        self.searchGstinValue = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchGstinValue.sizePolicy().hasHeightForWidth())
        self.searchGstinValue.setSizePolicy(sizePolicy)
        self.searchGstinValue.setMinimumSize(QtCore.QSize(350, 35))
        self.searchGstinValue.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.searchGstinValue.setObjectName("searchGstinValue")
        self.gridLayout_4.addWidget(self.searchGstinValue, 0, 3, 1, 1)
        self.searchButton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchButton.sizePolicy().hasHeightForWidth())
        self.searchButton.setSizePolicy(sizePolicy)
        self.searchButton.setMinimumSize(QtCore.QSize(200, 35))
        self.searchButton.setObjectName("searchButton")
        self.gridLayout_4.addWidget(self.searchButton, 0, 4, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 2)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.removeButton = QtGui.QPushButton(addCustomer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeButton.sizePolicy().hasHeightForWidth())
        self.removeButton.setSizePolicy(sizePolicy)
        self.removeButton.setMinimumSize(QtCore.QSize(0, 35))
        self.removeButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.removeButton.setObjectName("removeButton")
        self.horizontalLayout_7.addWidget(self.removeButton)
        self.clearButton = QtGui.QPushButton(addCustomer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearButton.sizePolicy().hasHeightForWidth())
        self.clearButton.setSizePolicy(sizePolicy)
        self.clearButton.setMinimumSize(QtCore.QSize(0, 35))
        self.clearButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout_7.addWidget(self.clearButton)
        self.importButton = QtGui.QPushButton(addCustomer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.importButton.sizePolicy().hasHeightForWidth())
        self.importButton.setSizePolicy(sizePolicy)
        self.importButton.setMinimumSize(QtCore.QSize(0, 35))
        self.importButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.importButton.setObjectName("importButton")
        self.horizontalLayout_7.addWidget(self.importButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 1, 0, 1, 2)
        self.customerTable = CustomerTable(addCustomer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customerTable.sizePolicy().hasHeightForWidth())
        self.customerTable.setSizePolicy(sizePolicy)
        self.customerTable.setObjectName("customerTable")
        self.gridLayout_2.addWidget(self.customerTable, 2, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(878, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 3, 0, 1, 1)
        self.tableSaveButton = QtGui.QPushButton(addCustomer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableSaveButton.sizePolicy().hasHeightForWidth())
        self.tableSaveButton.setSizePolicy(sizePolicy)
        self.tableSaveButton.setMinimumSize(QtCore.QSize(200, 35))
        self.tableSaveButton.setObjectName("tableSaveButton")
        self.gridLayout_2.addWidget(self.tableSaveButton, 3, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 1, 1, 1)

        self.retranslateUi(addCustomer)
        QtCore.QMetaObject.connectSlotsByName(addCustomer)

    def retranslateUi(self, addCustomer):
        addCustomer.setWindowTitle(QtGui.QApplication.translate("addCustomer", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.inputGroupBox.setTitle(QtGui.QApplication.translate("addCustomer", "Customer Details", None, QtGui.QApplication.UnicodeUTF8))
        self.customerCodeLabel.setText(QtGui.QApplication.translate("addCustomer", "Customer Code", None, QtGui.QApplication.UnicodeUTF8))
        self.customerCodeValue.setPlaceholderText(QtGui.QApplication.translate("addCustomer", "Enter Customer Code", None, QtGui.QApplication.UnicodeUTF8))
        self.codeMandLabel.setText(QtGui.QApplication.translate("addCustomer", "* Code is Mandatory", None, QtGui.QApplication.UnicodeUTF8))
        self.customerNameLabel.setText(QtGui.QApplication.translate("addCustomer", "Customer Name", None, QtGui.QApplication.UnicodeUTF8))
        self.customerNameValue.setPlaceholderText(QtGui.QApplication.translate("addCustomer", "Enter Customer Name", None, QtGui.QApplication.UnicodeUTF8))
        self.nameMandLabel.setText(QtGui.QApplication.translate("addCustomer", "* Nameis Mandatory", None, QtGui.QApplication.UnicodeUTF8))
        self.customerAddressLabel.setText(QtGui.QApplication.translate("addCustomer", "Customer Address", None, QtGui.QApplication.UnicodeUTF8))
        self.customerAddressValue.setPlaceholderText(QtGui.QApplication.translate("addCustomer", "Enter Customer Address", None, QtGui.QApplication.UnicodeUTF8))
        self.addressMandLabel.setText(QtGui.QApplication.translate("addCustomer", "*Address  is Mandatory", None, QtGui.QApplication.UnicodeUTF8))
        self.gstinLabel.setText(QtGui.QApplication.translate("addCustomer", "Customer GSTIN", None, QtGui.QApplication.UnicodeUTF8))
        self.customerGstinValue.setPlaceholderText(QtGui.QApplication.translate("addCustomer", "Enter Customer GSTIN", None, QtGui.QApplication.UnicodeUTF8))
        self.gstinMandLabel.setText(QtGui.QApplication.translate("addCustomer", "* GSTIN is Mandatory", None, QtGui.QApplication.UnicodeUTF8))
        self.stateCodeLabel.setText(QtGui.QApplication.translate("addCustomer", "State Code", None, QtGui.QApplication.UnicodeUTF8))
        self.stateCodeValue.setPlaceholderText(QtGui.QApplication.translate("addCustomer", "Enter state code", None, QtGui.QApplication.UnicodeUTF8))
        self.stateMandLabel.setText(QtGui.QApplication.translate("addCustomer", "* State Code is Mandatory", None, QtGui.QApplication.UnicodeUTF8))
        self.contactNoLabel.setText(QtGui.QApplication.translate("addCustomer", "Contact No", None, QtGui.QApplication.UnicodeUTF8))
        self.contactNoValue.setPlaceholderText(QtGui.QApplication.translate("addCustomer", "Enter contact no", None, QtGui.QApplication.UnicodeUTF8))
        self.contactMandLabel.setText(QtGui.QApplication.translate("addCustomer", "* Contact No is Mandatory", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("addCustomer", "Save Changes", None, QtGui.QApplication.UnicodeUTF8))
        self.discardButton.setText(QtGui.QApplication.translate("addCustomer", "Discard", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("addCustomer", "Search ", None, QtGui.QApplication.UnicodeUTF8))
        self.voucherNoLabel_2.setText(QtGui.QApplication.translate("addCustomer", "Customer name", None, QtGui.QApplication.UnicodeUTF8))
        self.searchNameValue.setPlaceholderText(QtGui.QApplication.translate("addCustomer", "Enter Name", None, QtGui.QApplication.UnicodeUTF8))
        self.gstinLabel_2.setText(QtGui.QApplication.translate("addCustomer", "GSTIN", None, QtGui.QApplication.UnicodeUTF8))
        self.searchGstinValue.setPlaceholderText(QtGui.QApplication.translate("addCustomer", "Enter Gstin", None, QtGui.QApplication.UnicodeUTF8))
        self.searchButton.setText(QtGui.QApplication.translate("addCustomer", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.removeButton.setText(QtGui.QApplication.translate("addCustomer", "Remove Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setText(QtGui.QApplication.translate("addCustomer", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.importButton.setText(QtGui.QApplication.translate("addCustomer", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.tableSaveButton.setText(QtGui.QApplication.translate("addCustomer", "Save Changes", None, QtGui.QApplication.UnicodeUTF8))

from _views.customerTableView import CustomerTable
from _widgets.header import Header
