# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'launcherUI.ui'
#
# Created: Sat Sep 29 21:30:36 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(916, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 916, 31))
        self.menubar.setObjectName("menubar")
        self.menuVoucher = QtGui.QMenu(self.menubar)
        self.menuVoucher.setObjectName("menuVoucher")
        self.menuAdd_Items = QtGui.QMenu(self.menubar)
        self.menuAdd_Items.setObjectName("menuAdd_Items")
        self.menuAdd_Customer = QtGui.QMenu(self.menubar)
        self.menuAdd_Customer.setObjectName("menuAdd_Customer")
        self.menuChart = QtGui.QMenu(self.menubar)
        self.menuChart.setObjectName("menuChart")
        self.menuQuotation = QtGui.QMenu(self.menubar)
        self.menuQuotation.setObjectName("menuQuotation")
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuPurchase_Order = QtGui.QMenu(self.menubar)
        self.menuPurchase_Order.setObjectName("menuPurchase_Order")
        self.menuPurchase = QtGui.QMenu(self.menubar)
        self.menuPurchase.setObjectName("menuPurchase")
        self.menuSales = QtGui.QMenu(self.menubar)
        self.menuSales.setObjectName("menuSales")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionDebit_Voucher = QtGui.QAction(MainWindow)
        self.actionDebit_Voucher.setObjectName("actionDebit_Voucher")
        self.actionCredit_Voucher = QtGui.QAction(MainWindow)
        self.actionCredit_Voucher.setObjectName("actionCredit_Voucher")
        self.actionSales_Item = QtGui.QAction(MainWindow)
        self.actionSales_Item.setObjectName("actionSales_Item")
        self.actionPurchase_Item = QtGui.QAction(MainWindow)
        self.actionPurchase_Item.setObjectName("actionPurchase_Item")
        self.actionCustomer_Details = QtGui.QAction(MainWindow)
        self.actionCustomer_Details.setObjectName("actionCustomer_Details")
        self.actionSales_Chart = QtGui.QAction(MainWindow)
        self.actionSales_Chart.setObjectName("actionSales_Chart")
        self.actionPurchase_Chart = QtGui.QAction(MainWindow)
        self.actionPurchase_Chart.setObjectName("actionPurchase_Chart")
        self.actionCreate_Quotation = QtGui.QAction(MainWindow)
        self.actionCreate_Quotation.setObjectName("actionCreate_Quotation")
        self.actionQuotation_Report = QtGui.QAction(MainWindow)
        self.actionQuotation_Report.setObjectName("actionQuotation_Report")
        self.actionAbout_Us = QtGui.QAction(MainWindow)
        self.actionAbout_Us.setObjectName("actionAbout_Us")
        self.actionCreate_Purchase_Order = QtGui.QAction(MainWindow)
        self.actionCreate_Purchase_Order.setObjectName("actionCreate_Purchase_Order")
        self.actionPurchase_Order_Report = QtGui.QAction(MainWindow)
        self.actionPurchase_Order_Report.setObjectName("actionPurchase_Order_Report")
        self.actionPurchase_Invoice = QtGui.QAction(MainWindow)
        self.actionPurchase_Invoice.setObjectName("actionPurchase_Invoice")
        self.actionPurchase_Report = QtGui.QAction(MainWindow)
        self.actionPurchase_Report.setObjectName("actionPurchase_Report")
        self.actionSales_Invoice = QtGui.QAction(MainWindow)
        self.actionSales_Invoice.setObjectName("actionSales_Invoice")
        self.actionSales_Report = QtGui.QAction(MainWindow)
        self.actionSales_Report.setObjectName("actionSales_Report")
        self.actionSaled_Item = QtGui.QAction(MainWindow)
        self.actionSaled_Item.setObjectName("actionSaled_Item")
        self.actionPurchased_Item = QtGui.QAction(MainWindow)
        self.actionPurchased_Item.setObjectName("actionPurchased_Item")
        self.actionPerforma_Invoice = QtGui.QAction(MainWindow)
        self.actionPerforma_Invoice.setObjectName("actionPerforma_Invoice")
        self.actionPerforma_Report = QtGui.QAction(MainWindow)
        self.actionPerforma_Report.setObjectName("actionPerforma_Report")
        self.menuVoucher.addAction(self.actionDebit_Voucher)
        self.menuVoucher.addSeparator()
        self.menuVoucher.addAction(self.actionCredit_Voucher)
        self.menuAdd_Items.addAction(self.actionSales_Item)
        self.menuAdd_Items.addSeparator()
        self.menuAdd_Items.addAction(self.actionPurchase_Item)
        self.menuAdd_Customer.addAction(self.actionCustomer_Details)
        self.menuChart.addAction(self.actionSales_Chart)
        self.menuChart.addAction(self.actionPurchase_Chart)
        self.menuChart.addSeparator()
        self.menuChart.addAction(self.actionSaled_Item)
        self.menuChart.addAction(self.actionPurchased_Item)
        self.menuQuotation.addAction(self.actionCreate_Quotation)
        self.menuQuotation.addSeparator()
        self.menuQuotation.addAction(self.actionQuotation_Report)
        self.menuAbout.addAction(self.actionAbout_Us)
        self.menuPurchase_Order.addSeparator()
        self.menuPurchase_Order.addAction(self.actionCreate_Purchase_Order)
        self.menuPurchase_Order.addSeparator()
        self.menuPurchase_Order.addAction(self.actionPurchase_Order_Report)
        self.menuPurchase.addAction(self.actionPurchase_Invoice)
        self.menuPurchase.addSeparator()
        self.menuPurchase.addAction(self.actionPurchase_Report)
        self.menuSales.addAction(self.actionSales_Invoice)
        self.menuSales.addAction(self.actionSales_Report)
        self.menuSales.addSeparator()
        self.menuSales.addAction(self.actionPerforma_Invoice)
        self.menuSales.addAction(self.actionPerforma_Report)
        self.menubar.addAction(self.menuSales.menuAction())
        self.menubar.addAction(self.menuPurchase.menuAction())
        self.menubar.addAction(self.menuQuotation.menuAction())
        self.menubar.addAction(self.menuPurchase_Order.menuAction())
        self.menubar.addAction(self.menuAdd_Customer.menuAction())
        self.menubar.addAction(self.menuAdd_Items.menuAction())
        self.menubar.addAction(self.menuVoucher.menuAction())
        self.menubar.addAction(self.menuChart.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.menuVoucher.setTitle(QtGui.QApplication.translate("MainWindow", "Voucher", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAdd_Items.setTitle(QtGui.QApplication.translate("MainWindow", "Add Items", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAdd_Customer.setTitle(QtGui.QApplication.translate("MainWindow", "Add Customer", None, QtGui.QApplication.UnicodeUTF8))
        self.menuChart.setTitle(QtGui.QApplication.translate("MainWindow", "Chart", None, QtGui.QApplication.UnicodeUTF8))
        self.menuQuotation.setTitle(QtGui.QApplication.translate("MainWindow", "Quotation", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPurchase_Order.setTitle(QtGui.QApplication.translate("MainWindow", "Purchase Order", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPurchase.setTitle(QtGui.QApplication.translate("MainWindow", "Purchase", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSales.setTitle(QtGui.QApplication.translate("MainWindow", "Sales", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDebit_Voucher.setText(QtGui.QApplication.translate("MainWindow", "Debit Voucher", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCredit_Voucher.setText(QtGui.QApplication.translate("MainWindow", "Credit Voucher", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSales_Item.setText(QtGui.QApplication.translate("MainWindow", "Sales Item", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPurchase_Item.setText(QtGui.QApplication.translate("MainWindow", "Purchase Item", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCustomer_Details.setText(QtGui.QApplication.translate("MainWindow", "Customer Details", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSales_Chart.setText(QtGui.QApplication.translate("MainWindow", "Sales Chart", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPurchase_Chart.setText(QtGui.QApplication.translate("MainWindow", "Purchase Chart", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCreate_Quotation.setText(QtGui.QApplication.translate("MainWindow", "Create Quotation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuotation_Report.setText(QtGui.QApplication.translate("MainWindow", "Quotation Report", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_Us.setText(QtGui.QApplication.translate("MainWindow", "About Us", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCreate_Purchase_Order.setText(QtGui.QApplication.translate("MainWindow", "Create Purchase Order", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPurchase_Order_Report.setText(QtGui.QApplication.translate("MainWindow", "Purchase Order Report", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPurchase_Invoice.setText(QtGui.QApplication.translate("MainWindow", "Purchase Invoice", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPurchase_Report.setText(QtGui.QApplication.translate("MainWindow", "Purchase Report", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSales_Invoice.setText(QtGui.QApplication.translate("MainWindow", "Sales Invoice", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSales_Report.setText(QtGui.QApplication.translate("MainWindow", "Sales Report", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaled_Item.setText(QtGui.QApplication.translate("MainWindow", "Saled Item", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPurchased_Item.setText(QtGui.QApplication.translate("MainWindow", "Purchased Item", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPerforma_Invoice.setText(QtGui.QApplication.translate("MainWindow", "Performa Invoice", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPerforma_Report.setText(QtGui.QApplication.translate("MainWindow", "Performa Report", None, QtGui.QApplication.UnicodeUTF8))

