# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\purchaseOrderReportUI.ui'
#
# Created: Sat Nov 24 16:32:45 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_purchaseOrderReport(object):
    def setupUi(self, purchaseOrderReport):
        purchaseOrderReport.setObjectName("purchaseOrderReport")
        purchaseOrderReport.resize(1716, 734)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(purchaseOrderReport.sizePolicy().hasHeightForWidth())
        purchaseOrderReport.setSizePolicy(sizePolicy)
        self.gridLayout = QtGui.QGridLayout(purchaseOrderReport)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = Header(purchaseOrderReport)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 2)
        self.groupBox = QtGui.QGroupBox(purchaseOrderReport)
        self.groupBox.setTitle("")
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.customerSearchValue = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customerSearchValue.sizePolicy().hasHeightForWidth())
        self.customerSearchValue.setSizePolicy(sizePolicy)
        self.customerSearchValue.setMinimumSize(QtCore.QSize(350, 35))
        self.customerSearchValue.setMaximumSize(QtCore.QSize(400, 16777215))
        self.customerSearchValue.setObjectName("customerSearchValue")
        self.horizontalLayout.addWidget(self.customerSearchValue)
        self.billSearchValue = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.billSearchValue.sizePolicy().hasHeightForWidth())
        self.billSearchValue.setSizePolicy(sizePolicy)
        self.billSearchValue.setMinimumSize(QtCore.QSize(0, 35))
        self.billSearchValue.setMaximumSize(QtCore.QSize(300, 16777215))
        self.billSearchValue.setObjectName("billSearchValue")
        self.horizontalLayout.addWidget(self.billSearchValue)
        self.fromDateLabel = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fromDateLabel.sizePolicy().hasHeightForWidth())
        self.fromDateLabel.setSizePolicy(sizePolicy)
        self.fromDateLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.fromDateLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.fromDateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.fromDateLabel.setObjectName("fromDateLabel")
        self.horizontalLayout.addWidget(self.fromDateLabel)
        self.fromDateValue = QtGui.QDateEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fromDateValue.sizePolicy().hasHeightForWidth())
        self.fromDateValue.setSizePolicy(sizePolicy)
        self.fromDateValue.setMinimumSize(QtCore.QSize(0, 35))
        self.fromDateValue.setMaximumSize(QtCore.QSize(250, 16777215))
        self.fromDateValue.setCalendarPopup(True)
        self.fromDateValue.setObjectName("fromDateValue")
        self.horizontalLayout.addWidget(self.fromDateValue)
        self.toDateLabel = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toDateLabel.sizePolicy().hasHeightForWidth())
        self.toDateLabel.setSizePolicy(sizePolicy)
        self.toDateLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.toDateLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.toDateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.toDateLabel.setObjectName("toDateLabel")
        self.horizontalLayout.addWidget(self.toDateLabel)
        self.toDateValue = QtGui.QDateEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toDateValue.sizePolicy().hasHeightForWidth())
        self.toDateValue.setSizePolicy(sizePolicy)
        self.toDateValue.setMinimumSize(QtCore.QSize(0, 35))
        self.toDateValue.setMaximumSize(QtCore.QSize(250, 16777215))
        self.toDateValue.setCalendarPopup(True)
        self.toDateValue.setObjectName("toDateValue")
        self.horizontalLayout.addWidget(self.toDateValue)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.searchButton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchButton.sizePolicy().hasHeightForWidth())
        self.searchButton.setSizePolicy(sizePolicy)
        self.searchButton.setMinimumSize(QtCore.QSize(0, 35))
        self.searchButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout_2.addWidget(self.searchButton)
        self.resetButton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resetButton.sizePolicy().hasHeightForWidth())
        self.resetButton.setSizePolicy(sizePolicy)
        self.resetButton.setMinimumSize(QtCore.QSize(0, 35))
        self.resetButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.resetButton.setObjectName("resetButton")
        self.horizontalLayout_2.addWidget(self.resetButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.removeButton = QtGui.QPushButton(purchaseOrderReport)
        self.removeButton.setMinimumSize(QtCore.QSize(200, 0))
        self.removeButton.setObjectName("removeButton")
        self.horizontalLayout_3.addWidget(self.removeButton)
        self.clearButton = QtGui.QPushButton(purchaseOrderReport)
        self.clearButton.setMinimumSize(QtCore.QSize(200, 0))
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout_3.addWidget(self.clearButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 2)
        self.purchaseOrderTable = PurchaseOrderReportTable(purchaseOrderReport)
        self.purchaseOrderTable.setObjectName("purchaseOrderTable")
        self.gridLayout.addWidget(self.purchaseOrderTable, 3, 0, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(1278, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 4, 0, 1, 1)
        self.saveButton = QtGui.QPushButton(purchaseOrderReport)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveButton.sizePolicy().hasHeightForWidth())
        self.saveButton.setSizePolicy(sizePolicy)
        self.saveButton.setMinimumSize(QtCore.QSize(400, 35))
        self.saveButton.setObjectName("saveButton")
        self.gridLayout.addWidget(self.saveButton, 4, 1, 1, 1)

        self.retranslateUi(purchaseOrderReport)
        QtCore.QMetaObject.connectSlotsByName(purchaseOrderReport)

    def retranslateUi(self, purchaseOrderReport):
        purchaseOrderReport.setWindowTitle(QtGui.QApplication.translate("purchaseOrderReport", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.customerSearchValue.setPlaceholderText(QtGui.QApplication.translate("purchaseOrderReport", "Enter Customer Name", None, QtGui.QApplication.UnicodeUTF8))
        self.billSearchValue.setPlaceholderText(QtGui.QApplication.translate("purchaseOrderReport", "Enter PO No", None, QtGui.QApplication.UnicodeUTF8))
        self.fromDateLabel.setText(QtGui.QApplication.translate("purchaseOrderReport", "From Date", None, QtGui.QApplication.UnicodeUTF8))
        self.fromDateValue.setDisplayFormat(QtGui.QApplication.translate("purchaseOrderReport", "dd-MMM-yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.toDateLabel.setText(QtGui.QApplication.translate("purchaseOrderReport", "To Date", None, QtGui.QApplication.UnicodeUTF8))
        self.toDateValue.setDisplayFormat(QtGui.QApplication.translate("purchaseOrderReport", "dd-MMM-yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.searchButton.setText(QtGui.QApplication.translate("purchaseOrderReport", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.resetButton.setText(QtGui.QApplication.translate("purchaseOrderReport", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.removeButton.setText(QtGui.QApplication.translate("purchaseOrderReport", "Remove Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setText(QtGui.QApplication.translate("purchaseOrderReport", "Clear Table", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("purchaseOrderReport", "Save", None, QtGui.QApplication.UnicodeUTF8))

from _views.purchaseOrderReportTableView import PurchaseOrderReportTable
from _widgets.header import Header
