# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\purchaseReportUI.ui'
#
# Created: Sun Nov 25 15:59:44 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_purchaseReport(object):
    def setupUi(self, purchaseReport):
        purchaseReport.setObjectName("purchaseReport")
        purchaseReport.resize(1716, 734)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(purchaseReport.sizePolicy().hasHeightForWidth())
        purchaseReport.setSizePolicy(sizePolicy)
        self.gridLayout = QtGui.QGridLayout(purchaseReport)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = Header(purchaseReport)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 2)
        self.groupBox = QtGui.QGroupBox(purchaseReport)
        self.groupBox.setTitle("")
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.customerSearchValue = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customerSearchValue.sizePolicy().hasHeightForWidth())
        self.customerSearchValue.setSizePolicy(sizePolicy)
        self.customerSearchValue.setMinimumSize(QtCore.QSize(350, 35))
        self.customerSearchValue.setMaximumSize(QtCore.QSize(400, 16777215))
        self.customerSearchValue.setObjectName("customerSearchValue")
        self.horizontalLayout_2.addWidget(self.customerSearchValue)
        self.billSearchValue = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.billSearchValue.sizePolicy().hasHeightForWidth())
        self.billSearchValue.setSizePolicy(sizePolicy)
        self.billSearchValue.setMinimumSize(QtCore.QSize(0, 35))
        self.billSearchValue.setMaximumSize(QtCore.QSize(300, 16777215))
        self.billSearchValue.setObjectName("billSearchValue")
        self.horizontalLayout_2.addWidget(self.billSearchValue)
        self.fromDateLabel = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fromDateLabel.sizePolicy().hasHeightForWidth())
        self.fromDateLabel.setSizePolicy(sizePolicy)
        self.fromDateLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.fromDateLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.fromDateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.fromDateLabel.setObjectName("fromDateLabel")
        self.horizontalLayout_2.addWidget(self.fromDateLabel)
        self.fromDateValue = QtGui.QDateEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fromDateValue.sizePolicy().hasHeightForWidth())
        self.fromDateValue.setSizePolicy(sizePolicy)
        self.fromDateValue.setMinimumSize(QtCore.QSize(0, 35))
        self.fromDateValue.setMaximumSize(QtCore.QSize(250, 16777215))
        self.fromDateValue.setCalendarPopup(True)
        self.fromDateValue.setObjectName("fromDateValue")
        self.horizontalLayout_2.addWidget(self.fromDateValue)
        self.toDateLabel = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toDateLabel.sizePolicy().hasHeightForWidth())
        self.toDateLabel.setSizePolicy(sizePolicy)
        self.toDateLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.toDateLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.toDateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.toDateLabel.setObjectName("toDateLabel")
        self.horizontalLayout_2.addWidget(self.toDateLabel)
        self.toDateValue = QtGui.QDateEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toDateValue.sizePolicy().hasHeightForWidth())
        self.toDateValue.setSizePolicy(sizePolicy)
        self.toDateValue.setMinimumSize(QtCore.QSize(0, 35))
        self.toDateValue.setMaximumSize(QtCore.QSize(250, 16777215))
        self.toDateValue.setCalendarPopup(True)
        self.toDateValue.setObjectName("toDateValue")
        self.horizontalLayout_2.addWidget(self.toDateValue)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchButton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchButton.sizePolicy().hasHeightForWidth())
        self.searchButton.setSizePolicy(sizePolicy)
        self.searchButton.setMinimumSize(QtCore.QSize(0, 35))
        self.searchButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout.addWidget(self.searchButton)
        self.resetButton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resetButton.sizePolicy().hasHeightForWidth())
        self.resetButton.setSizePolicy(sizePolicy)
        self.resetButton.setMinimumSize(QtCore.QSize(0, 35))
        self.resetButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.resetButton.setObjectName("resetButton")
        self.horizontalLayout.addWidget(self.resetButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.removeButton = QtGui.QPushButton(purchaseReport)
        self.removeButton.setMinimumSize(QtCore.QSize(200, 0))
        self.removeButton.setObjectName("removeButton")
        self.horizontalLayout_4.addWidget(self.removeButton)
        self.clearButton = QtGui.QPushButton(purchaseReport)
        self.clearButton.setMinimumSize(QtCore.QSize(200, 0))
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout_4.addWidget(self.clearButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 0, 1, 2)
        self.purchaseReportTable = PurchaseReportTable(purchaseReport)
        self.purchaseReportTable.setAlternatingRowColors(True)
        self.purchaseReportTable.setObjectName("purchaseReportTable")
        self.gridLayout.addWidget(self.purchaseReportTable, 3, 0, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(1278, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 4, 0, 1, 1)
        self.saveButton = QtGui.QPushButton(purchaseReport)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveButton.sizePolicy().hasHeightForWidth())
        self.saveButton.setSizePolicy(sizePolicy)
        self.saveButton.setMinimumSize(QtCore.QSize(400, 35))
        self.saveButton.setObjectName("saveButton")
        self.gridLayout.addWidget(self.saveButton, 4, 1, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.amountLabel = QtGui.QLabel(purchaseReport)
        self.amountLabel.setObjectName("amountLabel")
        self.horizontalLayout_3.addWidget(self.amountLabel)
        self.amountValue = QtGui.QLineEdit(purchaseReport)
        self.amountValue.setMinimumSize(QtCore.QSize(0, 35))
        self.amountValue.setReadOnly(True)
        self.amountValue.setObjectName("amountValue")
        self.horizontalLayout_3.addWidget(self.amountValue)
        self.taxLabel = QtGui.QLabel(purchaseReport)
        self.taxLabel.setObjectName("taxLabel")
        self.horizontalLayout_3.addWidget(self.taxLabel)
        self.taxValue = QtGui.QLineEdit(purchaseReport)
        self.taxValue.setMinimumSize(QtCore.QSize(0, 35))
        self.taxValue.setReadOnly(True)
        self.taxValue.setObjectName("taxValue")
        self.horizontalLayout_3.addWidget(self.taxValue)
        self.totalLabel = QtGui.QLabel(purchaseReport)
        self.totalLabel.setObjectName("totalLabel")
        self.horizontalLayout_3.addWidget(self.totalLabel)
        self.totalValue = QtGui.QLineEdit(purchaseReport)
        self.totalValue.setMinimumSize(QtCore.QSize(0, 35))
        self.totalValue.setReadOnly(True)
        self.totalValue.setObjectName("totalValue")
        self.horizontalLayout_3.addWidget(self.totalValue)
        self.amountPaidLabel = QtGui.QLabel(purchaseReport)
        self.amountPaidLabel.setObjectName("amountPaidLabel")
        self.horizontalLayout_3.addWidget(self.amountPaidLabel)
        self.amountPaidValue = QtGui.QLineEdit(purchaseReport)
        self.amountPaidValue.setMinimumSize(QtCore.QSize(0, 35))
        self.amountPaidValue.setReadOnly(True)
        self.amountPaidValue.setObjectName("amountPaidValue")
        self.horizontalLayout_3.addWidget(self.amountPaidValue)
        self.balanceLabel = QtGui.QLabel(purchaseReport)
        self.balanceLabel.setObjectName("balanceLabel")
        self.horizontalLayout_3.addWidget(self.balanceLabel)
        self.balanceValue = QtGui.QLineEdit(purchaseReport)
        self.balanceValue.setMinimumSize(QtCore.QSize(0, 35))
        self.balanceValue.setReadOnly(True)
        self.balanceValue.setObjectName("balanceValue")
        self.horizontalLayout_3.addWidget(self.balanceValue)
        self.gridLayout.addLayout(self.horizontalLayout_3, 5, 0, 1, 2)

        self.retranslateUi(purchaseReport)
        QtCore.QMetaObject.connectSlotsByName(purchaseReport)

    def retranslateUi(self, purchaseReport):
        purchaseReport.setWindowTitle(QtGui.QApplication.translate("purchaseReport", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.customerSearchValue.setPlaceholderText(QtGui.QApplication.translate("purchaseReport", "Enter Customer Name", None, QtGui.QApplication.UnicodeUTF8))
        self.billSearchValue.setPlaceholderText(QtGui.QApplication.translate("purchaseReport", "Enter bill No", None, QtGui.QApplication.UnicodeUTF8))
        self.fromDateLabel.setText(QtGui.QApplication.translate("purchaseReport", "From Date", None, QtGui.QApplication.UnicodeUTF8))
        self.fromDateValue.setDisplayFormat(QtGui.QApplication.translate("purchaseReport", "dd-MMM-yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.toDateLabel.setText(QtGui.QApplication.translate("purchaseReport", "To Date", None, QtGui.QApplication.UnicodeUTF8))
        self.toDateValue.setDisplayFormat(QtGui.QApplication.translate("purchaseReport", "dd-MMM-yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.searchButton.setText(QtGui.QApplication.translate("purchaseReport", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.resetButton.setText(QtGui.QApplication.translate("purchaseReport", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.removeButton.setText(QtGui.QApplication.translate("purchaseReport", "Remove Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setText(QtGui.QApplication.translate("purchaseReport", "Clear Table", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("purchaseReport", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.amountLabel.setText(QtGui.QApplication.translate("purchaseReport", "Amount", None, QtGui.QApplication.UnicodeUTF8))
        self.taxLabel.setText(QtGui.QApplication.translate("purchaseReport", "Tax", None, QtGui.QApplication.UnicodeUTF8))
        self.totalLabel.setText(QtGui.QApplication.translate("purchaseReport", "Total", None, QtGui.QApplication.UnicodeUTF8))
        self.amountPaidLabel.setText(QtGui.QApplication.translate("purchaseReport", "Amount Paid", None, QtGui.QApplication.UnicodeUTF8))
        self.balanceLabel.setText(QtGui.QApplication.translate("purchaseReport", "Balance", None, QtGui.QApplication.UnicodeUTF8))

from _views.purchaseReportTableView import PurchaseReportTable
from _widgets.header import Header
