# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\purchaseInvoiceUI.ui'
#
# Created: Sat Nov 24 16:32:18 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_PurchaseInvoice(object):
    def setupUi(self, PurchaseInvoice):
        PurchaseInvoice.setObjectName("PurchaseInvoice")
        PurchaseInvoice.resize(1398, 734)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PurchaseInvoice.sizePolicy().hasHeightForWidth())
        PurchaseInvoice.setSizePolicy(sizePolicy)
        self.gridLayout_3 = QtGui.QGridLayout(PurchaseInvoice)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget = Header(PurchaseInvoice)
        self.widget.setObjectName("widget")
        self.gridLayout_3.addWidget(self.widget, 0, 0, 1, 2)
        self.groupBox = QtGui.QGroupBox(PurchaseInvoice)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle("")
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.customerNameLabel = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customerNameLabel.sizePolicy().hasHeightForWidth())
        self.customerNameLabel.setSizePolicy(sizePolicy)
        self.customerNameLabel.setMinimumSize(QtCore.QSize(150, 30))
        self.customerNameLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.customerNameLabel.setObjectName("customerNameLabel")
        self.gridLayout.addWidget(self.customerNameLabel, 0, 0, 1, 1)
        self.customerNameValue = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customerNameValue.sizePolicy().hasHeightForWidth())
        self.customerNameValue.setSizePolicy(sizePolicy)
        self.customerNameValue.setMinimumSize(QtCore.QSize(200, 35))
        self.customerNameValue.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.customerNameValue.setObjectName("customerNameValue")
        self.gridLayout.addWidget(self.customerNameValue, 0, 1, 1, 1)
        self.customerAddressLabel = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customerAddressLabel.sizePolicy().hasHeightForWidth())
        self.customerAddressLabel.setSizePolicy(sizePolicy)
        self.customerAddressLabel.setMinimumSize(QtCore.QSize(150, 30))
        self.customerAddressLabel.setObjectName("customerAddressLabel")
        self.gridLayout.addWidget(self.customerAddressLabel, 1, 0, 1, 1)
        self.customerAddressValue = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customerAddressValue.sizePolicy().hasHeightForWidth())
        self.customerAddressValue.setSizePolicy(sizePolicy)
        self.customerAddressValue.setMinimumSize(QtCore.QSize(350, 35))
        self.customerAddressValue.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.customerAddressValue.setObjectName("customerAddressValue")
        self.gridLayout.addWidget(self.customerAddressValue, 1, 1, 2, 1)
        self.gstinLabel = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gstinLabel.sizePolicy().hasHeightForWidth())
        self.gstinLabel.setSizePolicy(sizePolicy)
        self.gstinLabel.setMinimumSize(QtCore.QSize(150, 30))
        self.gstinLabel.setObjectName("gstinLabel")
        self.gridLayout.addWidget(self.gstinLabel, 2, 0, 2, 1)
        self.gstinValue = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gstinValue.sizePolicy().hasHeightForWidth())
        self.gstinValue.setSizePolicy(sizePolicy)
        self.gstinValue.setMinimumSize(QtCore.QSize(200, 35))
        self.gstinValue.setObjectName("gstinValue")
        self.gridLayout.addWidget(self.gstinValue, 3, 1, 2, 1)
        self.stateCodeLabel = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stateCodeLabel.sizePolicy().hasHeightForWidth())
        self.stateCodeLabel.setSizePolicy(sizePolicy)
        self.stateCodeLabel.setMinimumSize(QtCore.QSize(150, 30))
        self.stateCodeLabel.setObjectName("stateCodeLabel")
        self.gridLayout.addWidget(self.stateCodeLabel, 4, 0, 2, 1)
        self.stateCodeValue = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stateCodeValue.sizePolicy().hasHeightForWidth())
        self.stateCodeValue.setSizePolicy(sizePolicy)
        self.stateCodeValue.setMinimumSize(QtCore.QSize(200, 35))
        self.stateCodeValue.setObjectName("stateCodeValue")
        self.gridLayout.addWidget(self.stateCodeValue, 5, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(PurchaseInvoice)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.billNoLabel = QtGui.QLabel(self.groupBox_2)
        self.billNoLabel.setMinimumSize(QtCore.QSize(150, 30))
        self.billNoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.billNoLabel.setObjectName("billNoLabel")
        self.gridLayout_4.addWidget(self.billNoLabel, 0, 0, 1, 1)
        self.billNoValue = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.billNoValue.sizePolicy().hasHeightForWidth())
        self.billNoValue.setSizePolicy(sizePolicy)
        self.billNoValue.setMinimumSize(QtCore.QSize(250, 30))
        self.billNoValue.setReadOnly(True)
        self.billNoValue.setObjectName("billNoValue")
        self.gridLayout_4.addWidget(self.billNoValue, 0, 1, 1, 1)
        self.billDateLabel = QtGui.QLabel(self.groupBox_2)
        self.billDateLabel.setMinimumSize(QtCore.QSize(150, 30))
        self.billDateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.billDateLabel.setObjectName("billDateLabel")
        self.gridLayout_4.addWidget(self.billDateLabel, 1, 0, 1, 1)
        self.billDateValue = QtGui.QDateEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.billDateValue.sizePolicy().hasHeightForWidth())
        self.billDateValue.setSizePolicy(sizePolicy)
        self.billDateValue.setMinimumSize(QtCore.QSize(250, 30))
        self.billDateValue.setCalendarPopup(True)
        self.billDateValue.setObjectName("billDateValue")
        self.gridLayout_4.addWidget(self.billDateValue, 1, 1, 1, 1)
        self.dueDateLabel = QtGui.QLabel(self.groupBox_2)
        self.dueDateLabel.setMinimumSize(QtCore.QSize(150, 30))
        self.dueDateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dueDateLabel.setObjectName("dueDateLabel")
        self.gridLayout_4.addWidget(self.dueDateLabel, 2, 0, 1, 1)
        self.dueDateValue = QtGui.QDateEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dueDateValue.sizePolicy().hasHeightForWidth())
        self.dueDateValue.setSizePolicy(sizePolicy)
        self.dueDateValue.setMinimumSize(QtCore.QSize(250, 30))
        self.dueDateValue.setCalendarPopup(True)
        self.dueDateValue.setObjectName("dueDateValue")
        self.gridLayout_4.addWidget(self.dueDateValue, 2, 1, 1, 1)
        self.paidByLabel = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paidByLabel.sizePolicy().hasHeightForWidth())
        self.paidByLabel.setSizePolicy(sizePolicy)
        self.paidByLabel.setMinimumSize(QtCore.QSize(150, 30))
        self.paidByLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.paidByLabel.setObjectName("paidByLabel")
        self.gridLayout_4.addWidget(self.paidByLabel, 3, 0, 1, 1)
        self.paymentValue = QtGui.QComboBox(self.groupBox_2)
        self.paymentValue.setObjectName("paymentValue")
        self.gridLayout_4.addWidget(self.paymentValue, 3, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 1, 1, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.addButton = QtGui.QPushButton(PurchaseInvoice)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(35)
        sizePolicy.setHeightForWidth(self.addButton.sizePolicy().hasHeightForWidth())
        self.addButton.setSizePolicy(sizePolicy)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout_4.addWidget(self.addButton)
        self.removeButton = QtGui.QPushButton(PurchaseInvoice)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(35)
        sizePolicy.setHeightForWidth(self.removeButton.sizePolicy().hasHeightForWidth())
        self.removeButton.setSizePolicy(sizePolicy)
        self.removeButton.setObjectName("removeButton")
        self.horizontalLayout_4.addWidget(self.removeButton)
        self.clearButton = QtGui.QPushButton(PurchaseInvoice)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(35)
        sizePolicy.setHeightForWidth(self.clearButton.sizePolicy().hasHeightForWidth())
        self.clearButton.setSizePolicy(sizePolicy)
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout_4.addWidget(self.clearButton)
        self.importButton = QtGui.QPushButton(PurchaseInvoice)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(35)
        sizePolicy.setHeightForWidth(self.importButton.sizePolicy().hasHeightForWidth())
        self.importButton.setSizePolicy(sizePolicy)
        self.importButton.setObjectName("importButton")
        self.horizontalLayout_4.addWidget(self.importButton)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 2, 0, 1, 2)
        self.purchaseTable = TableWidget(PurchaseInvoice)
        self.purchaseTable.setObjectName("purchaseTable")
        self.purchaseTable.setColumnCount(0)
        self.purchaseTable.setRowCount(0)
        self.gridLayout_3.addWidget(self.purchaseTable, 3, 0, 1, 2)
        self.groupBox_3 = QtGui.QGroupBox(PurchaseInvoice)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 40))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 210))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.beforeTaxLabel = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.beforeTaxLabel.sizePolicy().hasHeightForWidth())
        self.beforeTaxLabel.setSizePolicy(sizePolicy)
        self.beforeTaxLabel.setMinimumSize(QtCore.QSize(300, 30))
        self.beforeTaxLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.beforeTaxLabel.setObjectName("beforeTaxLabel")
        self.verticalLayout.addWidget(self.beforeTaxLabel)
        self.beforeTaxValue = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.beforeTaxValue.sizePolicy().hasHeightForWidth())
        self.beforeTaxValue.setSizePolicy(sizePolicy)
        self.beforeTaxValue.setMinimumSize(QtCore.QSize(300, 35))
        self.beforeTaxValue.setReadOnly(True)
        self.beforeTaxValue.setObjectName("beforeTaxValue")
        self.verticalLayout.addWidget(self.beforeTaxValue)
        self.afterTaxLabel = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.afterTaxLabel.sizePolicy().hasHeightForWidth())
        self.afterTaxLabel.setSizePolicy(sizePolicy)
        self.afterTaxLabel.setMinimumSize(QtCore.QSize(300, 30))
        self.afterTaxLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.afterTaxLabel.setObjectName("afterTaxLabel")
        self.verticalLayout.addWidget(self.afterTaxLabel)
        self.afterTaxValue = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.afterTaxValue.sizePolicy().hasHeightForWidth())
        self.afterTaxValue.setSizePolicy(sizePolicy)
        self.afterTaxValue.setMinimumSize(QtCore.QSize(300, 35))
        self.afterTaxValue.setReadOnly(True)
        self.afterTaxValue.setObjectName("afterTaxValue")
        self.verticalLayout.addWidget(self.afterTaxValue)
        self.gridLayout_6.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.amountPaidLabel = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.amountPaidLabel.sizePolicy().hasHeightForWidth())
        self.amountPaidLabel.setSizePolicy(sizePolicy)
        self.amountPaidLabel.setMinimumSize(QtCore.QSize(150, 30))
        self.amountPaidLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.amountPaidLabel.setObjectName("amountPaidLabel")
        self.horizontalLayout.addWidget(self.amountPaidLabel)
        self.amountPaidValue = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.amountPaidValue.sizePolicy().hasHeightForWidth())
        self.amountPaidValue.setSizePolicy(sizePolicy)
        self.amountPaidValue.setMinimumSize(QtCore.QSize(150, 30))
        self.amountPaidValue.setObjectName("amountPaidValue")
        self.horizontalLayout.addWidget(self.amountPaidValue)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.taxValueLabel = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.taxValueLabel.sizePolicy().hasHeightForWidth())
        self.taxValueLabel.setSizePolicy(sizePolicy)
        self.taxValueLabel.setMinimumSize(QtCore.QSize(150, 30))
        self.taxValueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.taxValueLabel.setObjectName("taxValueLabel")
        self.horizontalLayout_3.addWidget(self.taxValueLabel)
        self.taxValue = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.taxValue.sizePolicy().hasHeightForWidth())
        self.taxValue.setSizePolicy(sizePolicy)
        self.taxValue.setMinimumSize(QtCore.QSize(150, 30))
        self.taxValue.setReadOnly(True)
        self.taxValue.setObjectName("taxValue")
        self.horizontalLayout_3.addWidget(self.taxValue)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.saveButton = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveButton.sizePolicy().hasHeightForWidth())
        self.saveButton.setSizePolicy(sizePolicy)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_2.addWidget(self.saveButton)
        self.discardButton = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.discardButton.sizePolicy().hasHeightForWidth())
        self.discardButton.setSizePolicy(sizePolicy)
        self.discardButton.setObjectName("discardButton")
        self.horizontalLayout_2.addWidget(self.discardButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout_6.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.remarksLabel = QtGui.QLabel(self.groupBox_3)
        self.remarksLabel.setMinimumSize(QtCore.QSize(150, 30))
        self.remarksLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.remarksLabel.setObjectName("remarksLabel")
        self.gridLayout_2.addWidget(self.remarksLabel, 0, 0, 1, 1)
        self.amountWordLabel = QtGui.QLabel(self.groupBox_3)
        self.amountWordLabel.setMinimumSize(QtCore.QSize(150, 30))
        self.amountWordLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.amountWordLabel.setObjectName("amountWordLabel")
        self.gridLayout_2.addWidget(self.amountWordLabel, 0, 1, 1, 1)
        self.remarksValue = QtGui.QTextEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remarksValue.sizePolicy().hasHeightForWidth())
        self.remarksValue.setSizePolicy(sizePolicy)
        self.remarksValue.setMinimumSize(QtCore.QSize(350, 40))
        self.remarksValue.setObjectName("remarksValue")
        self.gridLayout_2.addWidget(self.remarksValue, 1, 0, 1, 1)
        self.amountWordsValue = QtGui.QTextEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.amountWordsValue.sizePolicy().hasHeightForWidth())
        self.amountWordsValue.setSizePolicy(sizePolicy)
        self.amountWordsValue.setMinimumSize(QtCore.QSize(350, 40))
        self.amountWordsValue.setReadOnly(True)
        self.amountWordsValue.setObjectName("amountWordsValue")
        self.gridLayout_2.addWidget(self.amountWordsValue, 1, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_2, 0, 2, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_3, 4, 0, 1, 2)

        self.retranslateUi(PurchaseInvoice)
        QtCore.QMetaObject.connectSlotsByName(PurchaseInvoice)

    def retranslateUi(self, PurchaseInvoice):
        PurchaseInvoice.setWindowTitle(QtGui.QApplication.translate("PurchaseInvoice", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.customerNameLabel.setText(QtGui.QApplication.translate("PurchaseInvoice", "Vendor Name", None, QtGui.QApplication.UnicodeUTF8))
        self.customerNameValue.setPlaceholderText(QtGui.QApplication.translate("PurchaseInvoice", "Enter Vendor Name", None, QtGui.QApplication.UnicodeUTF8))
        self.customerAddressLabel.setText(QtGui.QApplication.translate("PurchaseInvoice", "Vendor Address", None, QtGui.QApplication.UnicodeUTF8))
        self.customerAddressValue.setPlaceholderText(QtGui.QApplication.translate("PurchaseInvoice", "Enter Vendor Address", None, QtGui.QApplication.UnicodeUTF8))
        self.gstinLabel.setText(QtGui.QApplication.translate("PurchaseInvoice", "GSTIN", None, QtGui.QApplication.UnicodeUTF8))
        self.gstinValue.setPlaceholderText(QtGui.QApplication.translate("PurchaseInvoice", "Enter GSTIN No", None, QtGui.QApplication.UnicodeUTF8))
        self.stateCodeLabel.setText(QtGui.QApplication.translate("PurchaseInvoice", "State Code", None, QtGui.QApplication.UnicodeUTF8))
        self.stateCodeValue.setPlaceholderText(QtGui.QApplication.translate("PurchaseInvoice", "Enter State Code", None, QtGui.QApplication.UnicodeUTF8))
        self.billNoLabel.setText(QtGui.QApplication.translate("PurchaseInvoice", "Bill no", None, QtGui.QApplication.UnicodeUTF8))
        self.billDateLabel.setText(QtGui.QApplication.translate("PurchaseInvoice", "Bill Date", None, QtGui.QApplication.UnicodeUTF8))
        self.dueDateLabel.setText(QtGui.QApplication.translate("PurchaseInvoice", "Due Date", None, QtGui.QApplication.UnicodeUTF8))
        self.paidByLabel.setText(QtGui.QApplication.translate("PurchaseInvoice", "Paid By", None, QtGui.QApplication.UnicodeUTF8))
        self.addButton.setText(QtGui.QApplication.translate("PurchaseInvoice", "Add Row", None, QtGui.QApplication.UnicodeUTF8))
        self.removeButton.setText(QtGui.QApplication.translate("PurchaseInvoice", "Clear Selected row", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setText(QtGui.QApplication.translate("PurchaseInvoice", "Clear Table", None, QtGui.QApplication.UnicodeUTF8))
        self.importButton.setText(QtGui.QApplication.translate("PurchaseInvoice", "Import Table", None, QtGui.QApplication.UnicodeUTF8))
        self.beforeTaxLabel.setText(QtGui.QApplication.translate("PurchaseInvoice", "Total Amount Before Tax", None, QtGui.QApplication.UnicodeUTF8))
        self.afterTaxLabel.setText(QtGui.QApplication.translate("PurchaseInvoice", "Total Amount After Tax", None, QtGui.QApplication.UnicodeUTF8))
        self.amountPaidLabel.setText(QtGui.QApplication.translate("PurchaseInvoice", "Amount Paid", None, QtGui.QApplication.UnicodeUTF8))
        self.amountPaidValue.setPlaceholderText(QtGui.QApplication.translate("PurchaseInvoice", "Enter Amount Paid", None, QtGui.QApplication.UnicodeUTF8))
        self.taxValueLabel.setText(QtGui.QApplication.translate("PurchaseInvoice", "Tax Value", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("PurchaseInvoice", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.discardButton.setText(QtGui.QApplication.translate("PurchaseInvoice", "Discard", None, QtGui.QApplication.UnicodeUTF8))
        self.remarksLabel.setText(QtGui.QApplication.translate("PurchaseInvoice", "Remarks", None, QtGui.QApplication.UnicodeUTF8))
        self.amountWordLabel.setText(QtGui.QApplication.translate("PurchaseInvoice", "Total Amount in words", None, QtGui.QApplication.UnicodeUTF8))

from _widgets.header import Header
from _widgets.utils import TableWidget
