# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quotationCheckUI.ui'
#
# Created: Sat Sep 29 14:02:04 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_quotation(object):
    def setupUi(self, quotation):
        quotation.setObjectName("quotation")
        quotation.resize(1596, 734)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(quotation.sizePolicy().hasHeightForWidth())
        quotation.setSizePolicy(sizePolicy)
        self.gridLayout_6 = QtGui.QGridLayout(quotation)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.widget = Header(quotation)
        self.widget.setObjectName("widget")
        self.gridLayout_6.addWidget(self.widget, 0, 0, 1, 2)
        self.groupBox = QtGui.QGroupBox(quotation)
        self.groupBox.setTitle("")
        self.groupBox.setCheckable(True)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.customerNameValue = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customerNameValue.sizePolicy().hasHeightForWidth())
        self.customerNameValue.setSizePolicy(sizePolicy)
        self.customerNameValue.setMinimumSize(QtCore.QSize(200, 35))
        self.customerNameValue.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.customerNameValue.setObjectName("customerNameValue")
        self.gridLayout.addWidget(self.customerNameValue, 0, 1, 1, 1)
        self.customerAddressValue = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customerAddressValue.sizePolicy().hasHeightForWidth())
        self.customerAddressValue.setSizePolicy(sizePolicy)
        self.customerAddressValue.setMinimumSize(QtCore.QSize(350, 35))
        self.customerAddressValue.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.customerAddressValue.setObjectName("customerAddressValue")
        self.gridLayout.addWidget(self.customerAddressValue, 1, 1, 1, 1)
        self.customerAddressLabel = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customerAddressLabel.sizePolicy().hasHeightForWidth())
        self.customerAddressLabel.setSizePolicy(sizePolicy)
        self.customerAddressLabel.setMinimumSize(QtCore.QSize(150, 30))
        self.customerAddressLabel.setObjectName("customerAddressLabel")
        self.gridLayout.addWidget(self.customerAddressLabel, 1, 0, 1, 1)
        self.customerNameLabel = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customerNameLabel.sizePolicy().hasHeightForWidth())
        self.customerNameLabel.setSizePolicy(sizePolicy)
        self.customerNameLabel.setMinimumSize(QtCore.QSize(150, 30))
        self.customerNameLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.customerNameLabel.setObjectName("customerNameLabel")
        self.gridLayout.addWidget(self.customerNameLabel, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(quotation)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setCheckable(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.quotationDateValue = QtGui.QDateEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quotationDateValue.sizePolicy().hasHeightForWidth())
        self.quotationDateValue.setSizePolicy(sizePolicy)
        self.quotationDateValue.setMinimumSize(QtCore.QSize(150, 30))
        self.quotationDateValue.setCalendarPopup(True)
        self.quotationDateValue.setObjectName("quotationDateValue")
        self.gridLayout_4.addWidget(self.quotationDateValue, 1, 1, 1, 1)
        self.quotationNoValue = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quotationNoValue.sizePolicy().hasHeightForWidth())
        self.quotationNoValue.setSizePolicy(sizePolicy)
        self.quotationNoValue.setMinimumSize(QtCore.QSize(250, 30))
        self.quotationNoValue.setReadOnly(True)
        self.quotationNoValue.setObjectName("quotationNoValue")
        self.gridLayout_4.addWidget(self.quotationNoValue, 0, 1, 1, 1)
        self.validUntilValue = QtGui.QDateEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.validUntilValue.sizePolicy().hasHeightForWidth())
        self.validUntilValue.setSizePolicy(sizePolicy)
        self.validUntilValue.setMinimumSize(QtCore.QSize(150, 30))
        self.validUntilValue.setCalendarPopup(True)
        self.validUntilValue.setObjectName("validUntilValue")
        self.gridLayout_4.addWidget(self.validUntilValue, 2, 1, 1, 1)
        self.billDatelabel = QtGui.QLabel(self.groupBox_2)
        self.billDatelabel.setMinimumSize(QtCore.QSize(150, 30))
        self.billDatelabel.setAlignment(QtCore.Qt.AlignCenter)
        self.billDatelabel.setObjectName("billDatelabel")
        self.gridLayout_4.addWidget(self.billDatelabel, 1, 0, 1, 1)
        self.billDatelabel_2 = QtGui.QLabel(self.groupBox_2)
        self.billDatelabel_2.setMinimumSize(QtCore.QSize(150, 30))
        self.billDatelabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.billDatelabel_2.setObjectName("billDatelabel_2")
        self.gridLayout_4.addWidget(self.billDatelabel_2, 2, 0, 1, 1)
        self.billNoLabel = QtGui.QLabel(self.groupBox_2)
        self.billNoLabel.setMinimumSize(QtCore.QSize(150, 30))
        self.billNoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.billNoLabel.setObjectName("billNoLabel")
        self.gridLayout_4.addWidget(self.billNoLabel, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_2, 1, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.addButton = QtGui.QPushButton(quotation)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(35)
        sizePolicy.setHeightForWidth(self.addButton.sizePolicy().hasHeightForWidth())
        self.addButton.setSizePolicy(sizePolicy)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout_2.addWidget(self.addButton)
        self.removeButton = QtGui.QPushButton(quotation)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(35)
        sizePolicy.setHeightForWidth(self.removeButton.sizePolicy().hasHeightForWidth())
        self.removeButton.setSizePolicy(sizePolicy)
        self.removeButton.setObjectName("removeButton")
        self.horizontalLayout_2.addWidget(self.removeButton)
        self.clearButton = QtGui.QPushButton(quotation)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(35)
        sizePolicy.setHeightForWidth(self.clearButton.sizePolicy().hasHeightForWidth())
        self.clearButton.setSizePolicy(sizePolicy)
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout_2.addWidget(self.clearButton)
        self.importButton = QtGui.QPushButton(quotation)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(35)
        sizePolicy.setHeightForWidth(self.importButton.sizePolicy().hasHeightForWidth())
        self.importButton.setSizePolicy(sizePolicy)
        self.importButton.setObjectName("importButton")
        self.horizontalLayout_2.addWidget(self.importButton)
        self.gridLayout_6.addLayout(self.horizontalLayout_2, 2, 0, 1, 2)
        self.quotationTable = TableWidget(quotation)
        self.quotationTable.setObjectName("quotationTable")
        self.quotationTable.setColumnCount(0)
        self.quotationTable.setRowCount(0)
        self.gridLayout_6.addWidget(self.quotationTable, 3, 0, 1, 2)
        self.groupBox_3 = QtGui.QGroupBox(quotation)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 40))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 150))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setCheckable(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.beforeTaxLabel = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.beforeTaxLabel.sizePolicy().hasHeightForWidth())
        self.beforeTaxLabel.setSizePolicy(sizePolicy)
        self.beforeTaxLabel.setMinimumSize(QtCore.QSize(300, 30))
        self.beforeTaxLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.beforeTaxLabel.setObjectName("beforeTaxLabel")
        self.gridLayout_3.addWidget(self.beforeTaxLabel, 0, 0, 1, 1)
        self.afterTaxLabel = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.afterTaxLabel.sizePolicy().hasHeightForWidth())
        self.afterTaxLabel.setSizePolicy(sizePolicy)
        self.afterTaxLabel.setMinimumSize(QtCore.QSize(300, 30))
        self.afterTaxLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.afterTaxLabel.setObjectName("afterTaxLabel")
        self.gridLayout_3.addWidget(self.afterTaxLabel, 0, 1, 1, 1)
        self.taxValueLabel = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.taxValueLabel.sizePolicy().hasHeightForWidth())
        self.taxValueLabel.setSizePolicy(sizePolicy)
        self.taxValueLabel.setMinimumSize(QtCore.QSize(150, 30))
        self.taxValueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.taxValueLabel.setObjectName("taxValueLabel")
        self.gridLayout_3.addWidget(self.taxValueLabel, 0, 2, 1, 1)
        self.beforeTaxValue = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.beforeTaxValue.sizePolicy().hasHeightForWidth())
        self.beforeTaxValue.setSizePolicy(sizePolicy)
        self.beforeTaxValue.setMinimumSize(QtCore.QSize(300, 35))
        self.beforeTaxValue.setReadOnly(True)
        self.beforeTaxValue.setObjectName("beforeTaxValue")
        self.gridLayout_3.addWidget(self.beforeTaxValue, 1, 0, 1, 1)
        self.afterTaxValue = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.afterTaxValue.sizePolicy().hasHeightForWidth())
        self.afterTaxValue.setSizePolicy(sizePolicy)
        self.afterTaxValue.setMinimumSize(QtCore.QSize(300, 35))
        self.afterTaxValue.setReadOnly(True)
        self.afterTaxValue.setObjectName("afterTaxValue")
        self.gridLayout_3.addWidget(self.afterTaxValue, 1, 1, 1, 1)
        self.taxValue = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.taxValue.sizePolicy().hasHeightForWidth())
        self.taxValue.setSizePolicy(sizePolicy)
        self.taxValue.setMinimumSize(QtCore.QSize(200, 40))
        self.taxValue.setReadOnly(True)
        self.taxValue.setObjectName("taxValue")
        self.gridLayout_3.addWidget(self.taxValue, 1, 2, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.remarksLabel = QtGui.QLabel(self.groupBox_3)
        self.remarksLabel.setMinimumSize(QtCore.QSize(150, 30))
        self.remarksLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.remarksLabel.setObjectName("remarksLabel")
        self.gridLayout_2.addWidget(self.remarksLabel, 0, 0, 1, 1)
        self.amountWordLabel = QtGui.QLabel(self.groupBox_3)
        self.amountWordLabel.setMinimumSize(QtCore.QSize(150, 30))
        self.amountWordLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.amountWordLabel.setObjectName("amountWordLabel")
        self.gridLayout_2.addWidget(self.amountWordLabel, 0, 1, 1, 1)
        self.remarksValue = QtGui.QTextEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remarksValue.sizePolicy().hasHeightForWidth())
        self.remarksValue.setSizePolicy(sizePolicy)
        self.remarksValue.setMinimumSize(QtCore.QSize(350, 40))
        self.remarksValue.setObjectName("remarksValue")
        self.gridLayout_2.addWidget(self.remarksValue, 1, 0, 1, 1)
        self.amountWordsValue = QtGui.QTextEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.amountWordsValue.sizePolicy().hasHeightForWidth())
        self.amountWordsValue.setSizePolicy(sizePolicy)
        self.amountWordsValue.setMinimumSize(QtCore.QSize(350, 40))
        self.amountWordsValue.setObjectName("amountWordsValue")
        self.gridLayout_2.addWidget(self.amountWordsValue, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 0, 1, 2, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.printCheckBox = QtGui.QCheckBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(35)
        sizePolicy.setHeightForWidth(self.printCheckBox.sizePolicy().hasHeightForWidth())
        self.printCheckBox.setSizePolicy(sizePolicy)
        self.printCheckBox.setObjectName("printCheckBox")
        self.horizontalLayout.addWidget(self.printCheckBox)
        self.previewButton = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(35)
        sizePolicy.setHeightForWidth(self.previewButton.sizePolicy().hasHeightForWidth())
        self.previewButton.setSizePolicy(sizePolicy)
        self.previewButton.setObjectName("previewButton")
        self.horizontalLayout.addWidget(self.previewButton)
        self.saveButton = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(35)
        sizePolicy.setHeightForWidth(self.saveButton.sizePolicy().hasHeightForWidth())
        self.saveButton.setSizePolicy(sizePolicy)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.discardButton = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(35)
        sizePolicy.setHeightForWidth(self.discardButton.sizePolicy().hasHeightForWidth())
        self.discardButton.setSizePolicy(sizePolicy)
        self.discardButton.setObjectName("discardButton")
        self.horizontalLayout.addWidget(self.discardButton)
        self.gridLayout_5.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_3, 4, 0, 1, 2)

        self.retranslateUi(quotation)
        QtCore.QMetaObject.connectSlotsByName(quotation)

    def retranslateUi(self, quotation):
        quotation.setWindowTitle(QtGui.QApplication.translate("quotation", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.customerNameValue.setPlaceholderText(QtGui.QApplication.translate("quotation", "Enter Customer Name", None, QtGui.QApplication.UnicodeUTF8))
        self.customerAddressValue.setPlaceholderText(QtGui.QApplication.translate("quotation", "Enter Customer Address", None, QtGui.QApplication.UnicodeUTF8))
        self.customerAddressLabel.setText(QtGui.QApplication.translate("quotation", "Customer Address", None, QtGui.QApplication.UnicodeUTF8))
        self.customerNameLabel.setText(QtGui.QApplication.translate("quotation", "Customer Name", None, QtGui.QApplication.UnicodeUTF8))
        self.billDatelabel.setText(QtGui.QApplication.translate("quotation", "Quotation Date", None, QtGui.QApplication.UnicodeUTF8))
        self.billDatelabel_2.setText(QtGui.QApplication.translate("quotation", "Valid Until", None, QtGui.QApplication.UnicodeUTF8))
        self.billNoLabel.setText(QtGui.QApplication.translate("quotation", "Quotation no", None, QtGui.QApplication.UnicodeUTF8))
        self.addButton.setText(QtGui.QApplication.translate("quotation", "Add Row", None, QtGui.QApplication.UnicodeUTF8))
        self.removeButton.setText(QtGui.QApplication.translate("quotation", "Remove Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setText(QtGui.QApplication.translate("quotation", "Clear Table", None, QtGui.QApplication.UnicodeUTF8))
        self.importButton.setText(QtGui.QApplication.translate("quotation", "Import Table", None, QtGui.QApplication.UnicodeUTF8))
        self.beforeTaxLabel.setText(QtGui.QApplication.translate("quotation", "Total Amount Before Tax", None, QtGui.QApplication.UnicodeUTF8))
        self.afterTaxLabel.setText(QtGui.QApplication.translate("quotation", "Total Amount After Tax", None, QtGui.QApplication.UnicodeUTF8))
        self.taxValueLabel.setText(QtGui.QApplication.translate("quotation", "Total Tax Value", None, QtGui.QApplication.UnicodeUTF8))
        self.remarksLabel.setText(QtGui.QApplication.translate("quotation", "Remarks", None, QtGui.QApplication.UnicodeUTF8))
        self.amountWordLabel.setText(QtGui.QApplication.translate("quotation", "Total Amount in words", None, QtGui.QApplication.UnicodeUTF8))
        self.printCheckBox.setText(QtGui.QApplication.translate("quotation", "Print", None, QtGui.QApplication.UnicodeUTF8))
        self.previewButton.setText(QtGui.QApplication.translate("quotation", "Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("quotation", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.discardButton.setText(QtGui.QApplication.translate("quotation", "Discard", None, QtGui.QApplication.UnicodeUTF8))

from _widgets.header import Header
from _widgets.utils import TableWidget
