# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\quotationReportUI.ui'
#
# Created: Sat Oct 06 22:05:50 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_quotationReport(object):
    def setupUi(self, quotationReport):
        quotationReport.setObjectName("quotationReport")
        quotationReport.resize(1716, 734)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(quotationReport.sizePolicy().hasHeightForWidth())
        quotationReport.setSizePolicy(sizePolicy)
        self.gridLayout = QtGui.QGridLayout(quotationReport)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_2 = Header(quotationReport)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout.addWidget(self.widget_2, 0, 0, 1, 2)
        self.groupBox = QtGui.QGroupBox(quotationReport)
        self.groupBox.setTitle("")
        self.groupBox.setCheckable(True)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.customerSearchValue = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customerSearchValue.sizePolicy().hasHeightForWidth())
        self.customerSearchValue.setSizePolicy(sizePolicy)
        self.customerSearchValue.setMinimumSize(QtCore.QSize(350, 35))
        self.customerSearchValue.setMaximumSize(QtCore.QSize(400, 16777215))
        self.customerSearchValue.setObjectName("customerSearchValue")
        self.horizontalLayout.addWidget(self.customerSearchValue)
        self.billSearchValue = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.billSearchValue.sizePolicy().hasHeightForWidth())
        self.billSearchValue.setSizePolicy(sizePolicy)
        self.billSearchValue.setMinimumSize(QtCore.QSize(0, 35))
        self.billSearchValue.setMaximumSize(QtCore.QSize(300, 16777215))
        self.billSearchValue.setObjectName("billSearchValue")
        self.horizontalLayout.addWidget(self.billSearchValue)
        self.fromDateLabel = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fromDateLabel.sizePolicy().hasHeightForWidth())
        self.fromDateLabel.setSizePolicy(sizePolicy)
        self.fromDateLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.fromDateLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.fromDateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.fromDateLabel.setObjectName("fromDateLabel")
        self.horizontalLayout.addWidget(self.fromDateLabel)
        self.fromDateValue = QtGui.QDateEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fromDateValue.sizePolicy().hasHeightForWidth())
        self.fromDateValue.setSizePolicy(sizePolicy)
        self.fromDateValue.setMinimumSize(QtCore.QSize(0, 35))
        self.fromDateValue.setMaximumSize(QtCore.QSize(250, 16777215))
        self.fromDateValue.setCalendarPopup(True)
        self.fromDateValue.setObjectName("fromDateValue")
        self.horizontalLayout.addWidget(self.fromDateValue)
        self.toDateLabel = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toDateLabel.sizePolicy().hasHeightForWidth())
        self.toDateLabel.setSizePolicy(sizePolicy)
        self.toDateLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.toDateLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.toDateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.toDateLabel.setObjectName("toDateLabel")
        self.horizontalLayout.addWidget(self.toDateLabel)
        self.toDateValue = QtGui.QDateEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toDateValue.sizePolicy().hasHeightForWidth())
        self.toDateValue.setSizePolicy(sizePolicy)
        self.toDateValue.setMinimumSize(QtCore.QSize(0, 35))
        self.toDateValue.setMaximumSize(QtCore.QSize(250, 16777215))
        self.toDateValue.setCalendarPopup(True)
        self.toDateValue.setObjectName("toDateValue")
        self.horizontalLayout.addWidget(self.toDateValue)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.searchButton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchButton.sizePolicy().hasHeightForWidth())
        self.searchButton.setSizePolicy(sizePolicy)
        self.searchButton.setMinimumSize(QtCore.QSize(0, 35))
        self.searchButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout_2.addWidget(self.searchButton)
        self.resetButton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resetButton.sizePolicy().hasHeightForWidth())
        self.resetButton.setSizePolicy(sizePolicy)
        self.resetButton.setMinimumSize(QtCore.QSize(0, 35))
        self.resetButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.resetButton.setObjectName("resetButton")
        self.horizontalLayout_2.addWidget(self.resetButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.removeButton = QtGui.QPushButton(quotationReport)
        self.removeButton.setMinimumSize(QtCore.QSize(200, 0))
        self.removeButton.setObjectName("removeButton")
        self.horizontalLayout_4.addWidget(self.removeButton)
        self.clearButton = QtGui.QPushButton(quotationReport)
        self.clearButton.setMinimumSize(QtCore.QSize(200, 0))
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout_4.addWidget(self.clearButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 0, 1, 2)
        self.quotationReportTable = QuotationReportTable(quotationReport)
        self.quotationReportTable.setObjectName("quotationReportTable")
        self.gridLayout.addWidget(self.quotationReportTable, 3, 0, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(1278, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 4, 0, 1, 1)
        self.saveButton = QtGui.QPushButton(quotationReport)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveButton.sizePolicy().hasHeightForWidth())
        self.saveButton.setSizePolicy(sizePolicy)
        self.saveButton.setMinimumSize(QtCore.QSize(400, 35))
        self.saveButton.setObjectName("saveButton")
        self.gridLayout.addWidget(self.saveButton, 4, 1, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.amountLabel = QtGui.QLabel(quotationReport)
        self.amountLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.amountLabel.setObjectName("amountLabel")
        self.horizontalLayout_3.addWidget(self.amountLabel)
        self.amountValue = QtGui.QLineEdit(quotationReport)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.amountValue.sizePolicy().hasHeightForWidth())
        self.amountValue.setSizePolicy(sizePolicy)
        self.amountValue.setMinimumSize(QtCore.QSize(0, 35))
        self.amountValue.setReadOnly(True)
        self.amountValue.setObjectName("amountValue")
        self.horizontalLayout_3.addWidget(self.amountValue)
        self.taxLabel = QtGui.QLabel(quotationReport)
        self.taxLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.taxLabel.setObjectName("taxLabel")
        self.horizontalLayout_3.addWidget(self.taxLabel)
        self.taxValue = QtGui.QLineEdit(quotationReport)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.taxValue.sizePolicy().hasHeightForWidth())
        self.taxValue.setSizePolicy(sizePolicy)
        self.taxValue.setMinimumSize(QtCore.QSize(0, 35))
        self.taxValue.setReadOnly(True)
        self.taxValue.setObjectName("taxValue")
        self.horizontalLayout_3.addWidget(self.taxValue)
        self.totalLabel = QtGui.QLabel(quotationReport)
        self.totalLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.totalLabel.setObjectName("totalLabel")
        self.horizontalLayout_3.addWidget(self.totalLabel)
        self.totalValue = QtGui.QLineEdit(quotationReport)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.totalValue.sizePolicy().hasHeightForWidth())
        self.totalValue.setSizePolicy(sizePolicy)
        self.totalValue.setMinimumSize(QtCore.QSize(0, 35))
        self.totalValue.setReadOnly(True)
        self.totalValue.setObjectName("totalValue")
        self.horizontalLayout_3.addWidget(self.totalValue)
        self.gridLayout.addLayout(self.horizontalLayout_3, 5, 0, 1, 2)

        self.retranslateUi(quotationReport)
        QtCore.QMetaObject.connectSlotsByName(quotationReport)

    def retranslateUi(self, quotationReport):
        quotationReport.setWindowTitle(QtGui.QApplication.translate("quotationReport", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.customerSearchValue.setPlaceholderText(QtGui.QApplication.translate("quotationReport", "Enter Vendor Name", None, QtGui.QApplication.UnicodeUTF8))
        self.billSearchValue.setPlaceholderText(QtGui.QApplication.translate("quotationReport", "Enter Quotation No", None, QtGui.QApplication.UnicodeUTF8))
        self.fromDateLabel.setText(QtGui.QApplication.translate("quotationReport", "From Date", None, QtGui.QApplication.UnicodeUTF8))
        self.fromDateValue.setDisplayFormat(QtGui.QApplication.translate("quotationReport", "dd-MMM-yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.toDateLabel.setText(QtGui.QApplication.translate("quotationReport", "To Date", None, QtGui.QApplication.UnicodeUTF8))
        self.toDateValue.setDisplayFormat(QtGui.QApplication.translate("quotationReport", "dd-MMM-yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.searchButton.setText(QtGui.QApplication.translate("quotationReport", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.resetButton.setText(QtGui.QApplication.translate("quotationReport", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.removeButton.setText(QtGui.QApplication.translate("quotationReport", "Remove Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setText(QtGui.QApplication.translate("quotationReport", "Clear Table", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("quotationReport", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.amountLabel.setText(QtGui.QApplication.translate("quotationReport", "Amount", None, QtGui.QApplication.UnicodeUTF8))
        self.taxLabel.setText(QtGui.QApplication.translate("quotationReport", "Tax", None, QtGui.QApplication.UnicodeUTF8))
        self.totalLabel.setText(QtGui.QApplication.translate("quotationReport", "Total", None, QtGui.QApplication.UnicodeUTF8))

from _widgets.header import Header
from _views.quotationReportTableView import QuotationReportTable
