# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'companyDetails.ui'
#
# Created: Mon Jul 23 20:57:23 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1058, 624)
        self.gridLayout_4 = QtGui.QGridLayout(Form)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.customerNameLabel = QtGui.QLabel(Form)
        self.customerNameLabel.setObjectName("customerNameLabel")
        self.gridLayout.addWidget(self.customerNameLabel, 0, 0, 1, 1)
        self.customerNameValue = QtGui.QLineEdit(Form)
        self.customerNameValue.setObjectName("customerNameValue")
        self.gridLayout.addWidget(self.customerNameValue, 0, 1, 1, 1)
        self.customerRowValue = QtGui.QLineEdit(Form)
        self.customerRowValue.setObjectName("customerRowValue")
        self.gridLayout.addWidget(self.customerRowValue, 0, 3, 1, 1)
        self.customerColLabel = QtGui.QLabel(Form)
        self.customerColLabel.setObjectName("customerColLabel")
        self.gridLayout.addWidget(self.customerColLabel, 0, 4, 1, 1)
        self.customerColValue = QtGui.QLineEdit(Form)
        self.customerColValue.setObjectName("customerColValue")
        self.gridLayout.addWidget(self.customerColValue, 0, 5, 1, 1)
        self.companyTagLabel = QtGui.QLabel(Form)
        self.companyTagLabel.setObjectName("companyTagLabel")
        self.gridLayout.addWidget(self.companyTagLabel, 1, 0, 1, 1)
        self.companyTagValue = QtGui.QLineEdit(Form)
        self.companyTagValue.setObjectName("companyTagValue")
        self.gridLayout.addWidget(self.companyTagValue, 1, 1, 1, 1)
        self.companyRowLabel = QtGui.QLabel(Form)
        self.companyRowLabel.setObjectName("companyRowLabel")
        self.gridLayout.addWidget(self.companyRowLabel, 1, 2, 1, 1)
        self.companyRowValue = QtGui.QLineEdit(Form)
        self.companyRowValue.setObjectName("companyRowValue")
        self.gridLayout.addWidget(self.companyRowValue, 1, 3, 1, 1)
        self.companyColLabel = QtGui.QLabel(Form)
        self.companyColLabel.setObjectName("companyColLabel")
        self.gridLayout.addWidget(self.companyColLabel, 1, 4, 1, 1)
        self.companyColValue = QtGui.QLineEdit(Form)
        self.companyColValue.setObjectName("companyColValue")
        self.gridLayout.addWidget(self.companyColValue, 1, 5, 1, 1)
        self.address1Label = QtGui.QLabel(Form)
        self.address1Label.setObjectName("address1Label")
        self.gridLayout.addWidget(self.address1Label, 2, 0, 1, 1)
        self.address1Value = QtGui.QLineEdit(Form)
        self.address1Value.setObjectName("address1Value")
        self.gridLayout.addWidget(self.address1Value, 2, 1, 1, 1)
        self.address1RowLabel = QtGui.QLabel(Form)
        self.address1RowLabel.setObjectName("address1RowLabel")
        self.gridLayout.addWidget(self.address1RowLabel, 2, 2, 1, 1)
        self.address1RowValue = QtGui.QLineEdit(Form)
        self.address1RowValue.setObjectName("address1RowValue")
        self.gridLayout.addWidget(self.address1RowValue, 2, 3, 1, 1)
        self.address1ColLabel = QtGui.QLabel(Form)
        self.address1ColLabel.setObjectName("address1ColLabel")
        self.gridLayout.addWidget(self.address1ColLabel, 2, 4, 1, 1)
        self.address1ColValue = QtGui.QLineEdit(Form)
        self.address1ColValue.setObjectName("address1ColValue")
        self.gridLayout.addWidget(self.address1ColValue, 2, 5, 1, 1)
        self.address2Label = QtGui.QLabel(Form)
        self.address2Label.setObjectName("address2Label")
        self.gridLayout.addWidget(self.address2Label, 3, 0, 1, 1)
        self.address2Value = QtGui.QLineEdit(Form)
        self.address2Value.setObjectName("address2Value")
        self.gridLayout.addWidget(self.address2Value, 3, 1, 1, 1)
        self.address2Row = QtGui.QLabel(Form)
        self.address2Row.setObjectName("address2Row")
        self.gridLayout.addWidget(self.address2Row, 3, 2, 1, 1)
        self.address2RowValue = QtGui.QLineEdit(Form)
        self.address2RowValue.setObjectName("address2RowValue")
        self.gridLayout.addWidget(self.address2RowValue, 3, 3, 1, 1)
        self.address2ColLabel = QtGui.QLabel(Form)
        self.address2ColLabel.setObjectName("address2ColLabel")
        self.gridLayout.addWidget(self.address2ColLabel, 3, 4, 1, 1)
        self.address2ColValue = QtGui.QLineEdit(Form)
        self.address2ColValue.setObjectName("address2ColValue")
        self.gridLayout.addWidget(self.address2ColValue, 3, 5, 1, 1)
        self.customerRowLabel = QtGui.QLabel(Form)
        self.customerRowLabel.setObjectName("customerRowLabel")
        self.gridLayout.addWidget(self.customerRowLabel, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bankCustomerNameValue = QtGui.QLineEdit(self.groupBox)
        self.bankCustomerNameValue.setObjectName("bankCustomerNameValue")
        self.verticalLayout.addWidget(self.bankCustomerNameValue)
        self.bankBranchNameValue = QtGui.QLineEdit(self.groupBox)
        self.bankBranchNameValue.setObjectName("bankBranchNameValue")
        self.verticalLayout.addWidget(self.bankBranchNameValue)
        self.bankAccountValue = QtGui.QLineEdit(self.groupBox)
        self.bankAccountValue.setObjectName("bankAccountValue")
        self.verticalLayout.addWidget(self.bankAccountValue)
        self.bankIfscValue = QtGui.QLineEdit(self.groupBox)
        self.bankIfscValue.setObjectName("bankIfscValue")
        self.verticalLayout.addWidget(self.bankIfscValue)
        self.bankStateNameValue = QtGui.QLineEdit(self.groupBox)
        self.bankStateNameValue.setObjectName("bankStateNameValue")
        self.verticalLayout.addWidget(self.bankStateNameValue)
        self.bankFontSizeValue = QtGui.QLineEdit(self.groupBox)
        self.bankFontSizeValue.setObjectName("bankFontSizeValue")
        self.verticalLayout.addWidget(self.bankFontSizeValue)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(Form)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.billNoValue = QtGui.QLineEdit(self.groupBox_2)
        self.billNoValue.setObjectName("billNoValue")
        self.verticalLayout_2.addWidget(self.billNoValue)
        self.performaBillNoValue = QtGui.QLineEdit(self.groupBox_2)
        self.performaBillNoValue.setObjectName("performaBillNoValue")
        self.verticalLayout_2.addWidget(self.performaBillNoValue)
        self.customerGstinValue = QtGui.QLineEdit(self.groupBox_2)
        self.customerGstinValue.setObjectName("customerGstinValue")
        self.verticalLayout_2.addWidget(self.customerGstinValue)
        self.contactNoValue = QtGui.QLineEdit(self.groupBox_2)
        self.contactNoValue.setObjectName("contactNoValue")
        self.verticalLayout_2.addWidget(self.contactNoValue)
        self.stateCodeValue = QtGui.QLineEdit(self.groupBox_2)
        self.stateCodeValue.setObjectName("stateCodeValue")
        self.verticalLayout_2.addWidget(self.stateCodeValue)
        self.dcRowValue = QtGui.QLineEdit(self.groupBox_2)
        self.dcRowValue.setObjectName("dcRowValue")
        self.verticalLayout_2.addWidget(self.dcRowValue)
        self.dcColValue = QtGui.QLineEdit(self.groupBox_2)
        self.dcColValue.setObjectName("dcColValue")
        self.verticalLayout_2.addWidget(self.dcColValue)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.saveButton = QtGui.QPushButton(Form)
        self.saveButton.setObjectName("saveButton")
        self.gridLayout_2.addWidget(self.saveButton, 1, 0, 1, 1)
        self.discardButton = QtGui.QPushButton(Form)
        self.discardButton.setObjectName("discardButton")
        self.gridLayout_2.addWidget(self.discardButton, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.customerNameLabel.setText(QtGui.QApplication.translate("Form", "Customer Name", None, QtGui.QApplication.UnicodeUTF8))
        self.customerRowValue.setText(QtGui.QApplication.translate("Form", "150", None, QtGui.QApplication.UnicodeUTF8))
        self.customerColLabel.setText(QtGui.QApplication.translate("Form", "Customer column", None, QtGui.QApplication.UnicodeUTF8))
        self.customerColValue.setText(QtGui.QApplication.translate("Form", "735", None, QtGui.QApplication.UnicodeUTF8))
        self.companyTagLabel.setText(QtGui.QApplication.translate("Form", "Company Tag", None, QtGui.QApplication.UnicodeUTF8))
        self.companyTagValue.setPlaceholderText(QtGui.QApplication.translate("Form", "Enter Company Tag", None, QtGui.QApplication.UnicodeUTF8))
        self.companyRowLabel.setText(QtGui.QApplication.translate("Form", "Company row", None, QtGui.QApplication.UnicodeUTF8))
        self.companyRowValue.setText(QtGui.QApplication.translate("Form", "175", None, QtGui.QApplication.UnicodeUTF8))
        self.companyColLabel.setText(QtGui.QApplication.translate("Form", "Company column", None, QtGui.QApplication.UnicodeUTF8))
        self.companyColValue.setText(QtGui.QApplication.translate("Form", "718", None, QtGui.QApplication.UnicodeUTF8))
        self.address1Label.setText(QtGui.QApplication.translate("Form", "Address1", None, QtGui.QApplication.UnicodeUTF8))
        self.address1Value.setPlaceholderText(QtGui.QApplication.translate("Form", "Enter Address", None, QtGui.QApplication.UnicodeUTF8))
        self.address1RowLabel.setText(QtGui.QApplication.translate("Form", "address1 row", None, QtGui.QApplication.UnicodeUTF8))
        self.address1RowValue.setText(QtGui.QApplication.translate("Form", "40", None, QtGui.QApplication.UnicodeUTF8))
        self.address1ColLabel.setText(QtGui.QApplication.translate("Form", "address1 column", None, QtGui.QApplication.UnicodeUTF8))
        self.address1ColValue.setText(QtGui.QApplication.translate("Form", "703", None, QtGui.QApplication.UnicodeUTF8))
        self.address2Label.setText(QtGui.QApplication.translate("Form", "Address 2", None, QtGui.QApplication.UnicodeUTF8))
        self.address2Value.setPlaceholderText(QtGui.QApplication.translate("Form", "Enter Address", None, QtGui.QApplication.UnicodeUTF8))
        self.address2Row.setText(QtGui.QApplication.translate("Form", "address2 row", None, QtGui.QApplication.UnicodeUTF8))
        self.address2RowValue.setText(QtGui.QApplication.translate("Form", "75", None, QtGui.QApplication.UnicodeUTF8))
        self.address2ColLabel.setText(QtGui.QApplication.translate("Form", "address2 column", None, QtGui.QApplication.UnicodeUTF8))
        self.address2ColValue.setText(QtGui.QApplication.translate("Form", "693", None, QtGui.QApplication.UnicodeUTF8))
        self.customerRowLabel.setText(QtGui.QApplication.translate("Form", "Customer row", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "Bank Details", None, QtGui.QApplication.UnicodeUTF8))
        self.bankCustomerNameValue.setPlaceholderText(QtGui.QApplication.translate("Form", "Enter Bank Customer Name", None, QtGui.QApplication.UnicodeUTF8))
        self.bankBranchNameValue.setPlaceholderText(QtGui.QApplication.translate("Form", "Enter Bank branch Name", None, QtGui.QApplication.UnicodeUTF8))
        self.bankAccountValue.setPlaceholderText(QtGui.QApplication.translate("Form", "Enter account no", None, QtGui.QApplication.UnicodeUTF8))
        self.bankIfscValue.setPlaceholderText(QtGui.QApplication.translate("Form", "Enter IFSC code", None, QtGui.QApplication.UnicodeUTF8))
        self.bankStateNameValue.setPlaceholderText(QtGui.QApplication.translate("Form", "Enter state name", None, QtGui.QApplication.UnicodeUTF8))
        self.bankFontSizeValue.setPlaceholderText(QtGui.QApplication.translate("Form", "Font size for bank", None, QtGui.QApplication.UnicodeUTF8))
        self.billNoValue.setPlaceholderText(QtGui.QApplication.translate("Form", "Enter Bill no", None, QtGui.QApplication.UnicodeUTF8))
        self.performaBillNoValue.setPlaceholderText(QtGui.QApplication.translate("Form", "Enter Performa Bill no", None, QtGui.QApplication.UnicodeUTF8))
        self.customerGstinValue.setPlaceholderText(QtGui.QApplication.translate("Form", "Enter Customer GSTIN", None, QtGui.QApplication.UnicodeUTF8))
        self.contactNoValue.setPlaceholderText(QtGui.QApplication.translate("Form", "Enter Contact No", None, QtGui.QApplication.UnicodeUTF8))
        self.stateCodeValue.setPlaceholderText(QtGui.QApplication.translate("Form", "Enter State Code", None, QtGui.QApplication.UnicodeUTF8))
        self.dcRowValue.setText(QtGui.QApplication.translate("Form", "180", None, QtGui.QApplication.UnicodeUTF8))
        self.dcColValue.setText(QtGui.QApplication.translate("Form", "725", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("Form", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.discardButton.setText(QtGui.QApplication.translate("Form", "Discard", None, QtGui.QApplication.UnicodeUTF8))

