# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\voucherUI.ui'
#
# Created: Sat Nov 24 16:34:32 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Voucher(object):
    def setupUi(self, Voucher):
        Voucher.setObjectName("Voucher")
        Voucher.resize(1385, 753)
        self.gridLayout_5 = QtGui.QGridLayout(Voucher)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget = Header(Voucher)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 100))
        self.widget.setObjectName("widget")
        self.gridLayout_3.addWidget(self.widget, 0, 0, 1, 2)
        self.inputGroupBox = QtGui.QGroupBox(Voucher)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputGroupBox.sizePolicy().hasHeightForWidth())
        self.inputGroupBox.setSizePolicy(sizePolicy)
        self.inputGroupBox.setMinimumSize(QtCore.QSize(434, 0))
        self.inputGroupBox.setCheckable(False)
        self.inputGroupBox.setObjectName("inputGroupBox")
        self.gridLayout = QtGui.QGridLayout(self.inputGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.voucherNoLabel = QtGui.QLabel(self.inputGroupBox)
        self.voucherNoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.voucherNoLabel.setObjectName("voucherNoLabel")
        self.horizontalLayout_5.addWidget(self.voucherNoLabel)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.voucherNoValue = QtGui.QLineEdit(self.inputGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.voucherNoValue.sizePolicy().hasHeightForWidth())
        self.voucherNoValue.setSizePolicy(sizePolicy)
        self.voucherNoValue.setMinimumSize(QtCore.QSize(200, 35))
        self.voucherNoValue.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.voucherNoValue.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.voucherNoValue.setObjectName("voucherNoValue")
        self.verticalLayout.addWidget(self.voucherNoValue)
        self.voucherMandLabel = QtGui.QLabel(self.inputGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.voucherMandLabel.sizePolicy().hasHeightForWidth())
        self.voucherMandLabel.setSizePolicy(sizePolicy)
        self.voucherMandLabel.setMinimumSize(QtCore.QSize(200, 30))
        self.voucherMandLabel.setStyleSheet("QLabel { color : red; }")
        self.voucherMandLabel.setObjectName("voucherMandLabel")
        self.verticalLayout.addWidget(self.voucherMandLabel)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout_5, 0, 0, 1, 2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.nameLabel = QtGui.QLabel(self.inputGroupBox)
        self.nameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel.setObjectName("nameLabel")
        self.horizontalLayout_6.addWidget(self.nameLabel)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.nameValue = QtGui.QLineEdit(self.inputGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nameValue.sizePolicy().hasHeightForWidth())
        self.nameValue.setSizePolicy(sizePolicy)
        self.nameValue.setMinimumSize(QtCore.QSize(200, 35))
        self.nameValue.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.nameValue.setObjectName("nameValue")
        self.verticalLayout_2.addWidget(self.nameValue)
        self.nameMandLabel = QtGui.QLabel(self.inputGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nameMandLabel.sizePolicy().hasHeightForWidth())
        self.nameMandLabel.setSizePolicy(sizePolicy)
        self.nameMandLabel.setMinimumSize(QtCore.QSize(200, 30))
        self.nameMandLabel.setStyleSheet("QLabel { color : red; }")
        self.nameMandLabel.setObjectName("nameMandLabel")
        self.verticalLayout_2.addWidget(self.nameMandLabel)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout_6, 1, 0, 1, 2)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.dateLabel = QtGui.QLabel(self.inputGroupBox)
        self.dateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dateLabel.setObjectName("dateLabel")
        self.horizontalLayout_7.addWidget(self.dateLabel)
        self.dateValue = QtGui.QDateEdit(self.inputGroupBox)
        self.dateValue.setMinimumSize(QtCore.QSize(200, 35))
        self.dateValue.setCalendarPopup(True)
        self.dateValue.setObjectName("dateValue")
        self.horizontalLayout_7.addWidget(self.dateValue)
        self.gridLayout.addLayout(self.horizontalLayout_7, 2, 0, 1, 2)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.remarksLabel = QtGui.QLabel(self.inputGroupBox)
        self.remarksLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.remarksLabel.setObjectName("remarksLabel")
        self.horizontalLayout_8.addWidget(self.remarksLabel)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.remarksValue = QtGui.QLineEdit(self.inputGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remarksValue.sizePolicy().hasHeightForWidth())
        self.remarksValue.setSizePolicy(sizePolicy)
        self.remarksValue.setMinimumSize(QtCore.QSize(200, 35))
        self.remarksValue.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.remarksValue.setObjectName("remarksValue")
        self.verticalLayout_3.addWidget(self.remarksValue)
        self.remarksMandLabel = QtGui.QLabel(self.inputGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remarksMandLabel.sizePolicy().hasHeightForWidth())
        self.remarksMandLabel.setSizePolicy(sizePolicy)
        self.remarksMandLabel.setMinimumSize(QtCore.QSize(200, 30))
        self.remarksMandLabel.setStyleSheet("QLabel { color : red; }")
        self.remarksMandLabel.setObjectName("remarksMandLabel")
        self.verticalLayout_3.addWidget(self.remarksMandLabel)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout_8, 3, 0, 1, 2)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.paymentTypeLabel = QtGui.QLabel(self.inputGroupBox)
        self.paymentTypeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.paymentTypeLabel.setObjectName("paymentTypeLabel")
        self.horizontalLayout_9.addWidget(self.paymentTypeLabel)
        self.paymentValue = QtGui.QComboBox(self.inputGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paymentValue.sizePolicy().hasHeightForWidth())
        self.paymentValue.setSizePolicy(sizePolicy)
        self.paymentValue.setMinimumSize(QtCore.QSize(200, 35))
        self.paymentValue.setObjectName("paymentValue")
        self.horizontalLayout_9.addWidget(self.paymentValue)
        self.gridLayout.addLayout(self.horizontalLayout_9, 4, 0, 1, 2)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.chequeLabel = QtGui.QLabel(self.inputGroupBox)
        self.chequeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.chequeLabel.setObjectName("chequeLabel")
        self.horizontalLayout_10.addWidget(self.chequeLabel)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.chequeNoValue = QtGui.QLineEdit(self.inputGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chequeNoValue.sizePolicy().hasHeightForWidth())
        self.chequeNoValue.setSizePolicy(sizePolicy)
        self.chequeNoValue.setMinimumSize(QtCore.QSize(200, 35))
        self.chequeNoValue.setReadOnly(True)
        self.chequeNoValue.setObjectName("chequeNoValue")
        self.verticalLayout_5.addWidget(self.chequeNoValue)
        self.chequeMandLabel = QtGui.QLabel(self.inputGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chequeMandLabel.sizePolicy().hasHeightForWidth())
        self.chequeMandLabel.setSizePolicy(sizePolicy)
        self.chequeMandLabel.setMinimumSize(QtCore.QSize(200, 30))
        self.chequeMandLabel.setStyleSheet("QLabel { color : red; }")
        self.chequeMandLabel.setObjectName("chequeMandLabel")
        self.verticalLayout_5.addWidget(self.chequeMandLabel)
        self.horizontalLayout_10.addLayout(self.verticalLayout_5)
        self.gridLayout.addLayout(self.horizontalLayout_10, 5, 0, 1, 2)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.amountLabel = QtGui.QLabel(self.inputGroupBox)
        self.amountLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.amountLabel.setObjectName("amountLabel")
        self.horizontalLayout_11.addWidget(self.amountLabel)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.amountValue = QtGui.QLineEdit(self.inputGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.amountValue.sizePolicy().hasHeightForWidth())
        self.amountValue.setSizePolicy(sizePolicy)
        self.amountValue.setMinimumSize(QtCore.QSize(200, 35))
        self.amountValue.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.amountValue.setObjectName("amountValue")
        self.verticalLayout_4.addWidget(self.amountValue)
        self.amountMandLabel = QtGui.QLabel(self.inputGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.amountMandLabel.sizePolicy().hasHeightForWidth())
        self.amountMandLabel.setSizePolicy(sizePolicy)
        self.amountMandLabel.setMinimumSize(QtCore.QSize(200, 35))
        self.amountMandLabel.setStyleSheet("QLabel { color : red; }")
        self.amountMandLabel.setObjectName("amountMandLabel")
        self.verticalLayout_4.addWidget(self.amountMandLabel)
        self.horizontalLayout_11.addLayout(self.verticalLayout_4)
        self.gridLayout.addLayout(self.horizontalLayout_11, 6, 0, 1, 2)
        self.saveButton = QtGui.QPushButton(self.inputGroupBox)
        self.saveButton.setMinimumSize(QtCore.QSize(200, 35))
        self.saveButton.setObjectName("saveButton")
        self.gridLayout.addWidget(self.saveButton, 7, 0, 1, 1)
        self.discardButton = QtGui.QPushButton(self.inputGroupBox)
        self.discardButton.setMinimumSize(QtCore.QSize(200, 35))
        self.discardButton.setObjectName("discardButton")
        self.gridLayout.addWidget(self.discardButton, 7, 1, 1, 1)
        self.gridLayout_3.addWidget(self.inputGroupBox, 1, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtGui.QGroupBox(Voucher)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.customerSearchValue = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customerSearchValue.sizePolicy().hasHeightForWidth())
        self.customerSearchValue.setSizePolicy(sizePolicy)
        self.customerSearchValue.setMinimumSize(QtCore.QSize(350, 35))
        self.customerSearchValue.setMaximumSize(QtCore.QSize(400, 16777215))
        self.customerSearchValue.setObjectName("customerSearchValue")
        self.horizontalLayout.addWidget(self.customerSearchValue)
        self.billSearchValue = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.billSearchValue.sizePolicy().hasHeightForWidth())
        self.billSearchValue.setSizePolicy(sizePolicy)
        self.billSearchValue.setMinimumSize(QtCore.QSize(0, 35))
        self.billSearchValue.setMaximumSize(QtCore.QSize(300, 16777215))
        self.billSearchValue.setObjectName("billSearchValue")
        self.horizontalLayout.addWidget(self.billSearchValue)
        self.fromDateLabel = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fromDateLabel.sizePolicy().hasHeightForWidth())
        self.fromDateLabel.setSizePolicy(sizePolicy)
        self.fromDateLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.fromDateLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.fromDateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.fromDateLabel.setObjectName("fromDateLabel")
        self.horizontalLayout.addWidget(self.fromDateLabel)
        self.fromDateValue = QtGui.QDateEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fromDateValue.sizePolicy().hasHeightForWidth())
        self.fromDateValue.setSizePolicy(sizePolicy)
        self.fromDateValue.setMinimumSize(QtCore.QSize(0, 35))
        self.fromDateValue.setMaximumSize(QtCore.QSize(250, 16777215))
        self.fromDateValue.setCalendarPopup(True)
        self.fromDateValue.setObjectName("fromDateValue")
        self.horizontalLayout.addWidget(self.fromDateValue)
        self.toDateLabel = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toDateLabel.sizePolicy().hasHeightForWidth())
        self.toDateLabel.setSizePolicy(sizePolicy)
        self.toDateLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.toDateLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.toDateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.toDateLabel.setObjectName("toDateLabel")
        self.horizontalLayout.addWidget(self.toDateLabel)
        self.toDateValue = QtGui.QDateEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toDateValue.sizePolicy().hasHeightForWidth())
        self.toDateValue.setSizePolicy(sizePolicy)
        self.toDateValue.setMinimumSize(QtCore.QSize(0, 35))
        self.toDateValue.setMaximumSize(QtCore.QSize(250, 16777215))
        self.toDateValue.setCalendarPopup(True)
        self.toDateValue.setObjectName("toDateValue")
        self.horizontalLayout.addWidget(self.toDateValue)
        self.gridLayout_4.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.searchButton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchButton.sizePolicy().hasHeightForWidth())
        self.searchButton.setSizePolicy(sizePolicy)
        self.searchButton.setMinimumSize(QtCore.QSize(400, 35))
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout_2.addWidget(self.searchButton)
        self.resetButton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resetButton.sizePolicy().hasHeightForWidth())
        self.resetButton.setSizePolicy(sizePolicy)
        self.resetButton.setMinimumSize(QtCore.QSize(400, 35))
        self.resetButton.setObjectName("resetButton")
        self.horizontalLayout_2.addWidget(self.resetButton)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 3)
        self.removeButton = QtGui.QPushButton(Voucher)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeButton.sizePolicy().hasHeightForWidth())
        self.removeButton.setSizePolicy(sizePolicy)
        self.removeButton.setMinimumSize(QtCore.QSize(0, 35))
        self.removeButton.setObjectName("removeButton")
        self.gridLayout_2.addWidget(self.removeButton, 1, 0, 1, 1)
        self.clearButton = QtGui.QPushButton(Voucher)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearButton.sizePolicy().hasHeightForWidth())
        self.clearButton.setSizePolicy(sizePolicy)
        self.clearButton.setMinimumSize(QtCore.QSize(0, 35))
        self.clearButton.setObjectName("clearButton")
        self.gridLayout_2.addWidget(self.clearButton, 1, 1, 1, 1)
        self.importButton = QtGui.QPushButton(Voucher)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.importButton.sizePolicy().hasHeightForWidth())
        self.importButton.setSizePolicy(sizePolicy)
        self.importButton.setMinimumSize(QtCore.QSize(0, 35))
        self.importButton.setObjectName("importButton")
        self.gridLayout_2.addWidget(self.importButton, 1, 2, 1, 1)
        self.voucherTable = VoucherTableView(Voucher)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.voucherTable.sizePolicy().hasHeightForWidth())
        self.voucherTable.setSizePolicy(sizePolicy)
        self.voucherTable.setObjectName("voucherTable")
        self.gridLayout_2.addWidget(self.voucherTable, 2, 0, 1, 3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtGui.QSpacerItem(500, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.saveTableButton = QtGui.QPushButton(Voucher)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveTableButton.sizePolicy().hasHeightForWidth())
        self.saveTableButton.setSizePolicy(sizePolicy)
        self.saveTableButton.setMinimumSize(QtCore.QSize(400, 35))
        self.saveTableButton.setObjectName("saveTableButton")
        self.horizontalLayout_4.addWidget(self.saveTableButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 3, 0, 1, 3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.totalAmountLabel = QtGui.QLabel(Voucher)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.totalAmountLabel.sizePolicy().hasHeightForWidth())
        self.totalAmountLabel.setSizePolicy(sizePolicy)
        self.totalAmountLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.totalAmountLabel.setObjectName("totalAmountLabel")
        self.horizontalLayout_3.addWidget(self.totalAmountLabel)
        self.totalAmountValue = QtGui.QLineEdit(Voucher)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.totalAmountValue.sizePolicy().hasHeightForWidth())
        self.totalAmountValue.setSizePolicy(sizePolicy)
        self.totalAmountValue.setReadOnly(True)
        self.totalAmountValue.setObjectName("totalAmountValue")
        self.horizontalLayout_3.addWidget(self.totalAmountValue)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 4, 0, 1, 3)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 0, 0, 1, 1)

        self.retranslateUi(Voucher)
        self.paymentValue.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Voucher)

    def retranslateUi(self, Voucher):
        Voucher.setWindowTitle(QtGui.QApplication.translate("Voucher", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.inputGroupBox.setTitle(QtGui.QApplication.translate("Voucher", "Creditor Details", None, QtGui.QApplication.UnicodeUTF8))
        self.voucherNoLabel.setText(QtGui.QApplication.translate("Voucher", "Voucher No", None, QtGui.QApplication.UnicodeUTF8))
        self.voucherNoValue.setPlaceholderText(QtGui.QApplication.translate("Voucher", "Enter Voucher No", None, QtGui.QApplication.UnicodeUTF8))
        self.voucherMandLabel.setText(QtGui.QApplication.translate("Voucher", "* Voucher No is Mandatory", None, QtGui.QApplication.UnicodeUTF8))
        self.nameLabel.setText(QtGui.QApplication.translate("Voucher", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.nameValue.setPlaceholderText(QtGui.QApplication.translate("Voucher", "Enter name", None, QtGui.QApplication.UnicodeUTF8))
        self.nameMandLabel.setText(QtGui.QApplication.translate("Voucher", "* Name is Mandatory", None, QtGui.QApplication.UnicodeUTF8))
        self.dateLabel.setText(QtGui.QApplication.translate("Voucher", "Credit Date", None, QtGui.QApplication.UnicodeUTF8))
        self.dateValue.setDisplayFormat(QtGui.QApplication.translate("Voucher", "dd-MMM-yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.remarksLabel.setText(QtGui.QApplication.translate("Voucher", "Remarks", None, QtGui.QApplication.UnicodeUTF8))
        self.remarksValue.setPlaceholderText(QtGui.QApplication.translate("Voucher", "Enter remarks", None, QtGui.QApplication.UnicodeUTF8))
        self.remarksMandLabel.setText(QtGui.QApplication.translate("Voucher", "* Remarks is mandatory", None, QtGui.QApplication.UnicodeUTF8))
        self.paymentTypeLabel.setText(QtGui.QApplication.translate("Voucher", "Select Payment Type", None, QtGui.QApplication.UnicodeUTF8))
        self.chequeLabel.setText(QtGui.QApplication.translate("Voucher", "Cheque No", None, QtGui.QApplication.UnicodeUTF8))
        self.chequeNoValue.setPlaceholderText(QtGui.QApplication.translate("Voucher", "Enter Cheque No", None, QtGui.QApplication.UnicodeUTF8))
        self.chequeMandLabel.setText(QtGui.QApplication.translate("Voucher", "* Cheque No is mandatory", None, QtGui.QApplication.UnicodeUTF8))
        self.amountLabel.setText(QtGui.QApplication.translate("Voucher", "Enter Amount", None, QtGui.QApplication.UnicodeUTF8))
        self.amountValue.setPlaceholderText(QtGui.QApplication.translate("Voucher", "Enter Amount", None, QtGui.QApplication.UnicodeUTF8))
        self.amountMandLabel.setText(QtGui.QApplication.translate("Voucher", "* Amount is Mandatory", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("Voucher", "Save Changes", None, QtGui.QApplication.UnicodeUTF8))
        self.discardButton.setText(QtGui.QApplication.translate("Voucher", "Discard", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Voucher", "Search ", None, QtGui.QApplication.UnicodeUTF8))
        self.customerSearchValue.setPlaceholderText(QtGui.QApplication.translate("Voucher", "Enter Name", None, QtGui.QApplication.UnicodeUTF8))
        self.billSearchValue.setPlaceholderText(QtGui.QApplication.translate("Voucher", "Enter Voucher No", None, QtGui.QApplication.UnicodeUTF8))
        self.fromDateLabel.setText(QtGui.QApplication.translate("Voucher", "From Date", None, QtGui.QApplication.UnicodeUTF8))
        self.fromDateValue.setDisplayFormat(QtGui.QApplication.translate("Voucher", "dd-MMM-yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.toDateLabel.setText(QtGui.QApplication.translate("Voucher", "To Date", None, QtGui.QApplication.UnicodeUTF8))
        self.toDateValue.setDisplayFormat(QtGui.QApplication.translate("Voucher", "dd-MMM-yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.searchButton.setText(QtGui.QApplication.translate("Voucher", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.resetButton.setText(QtGui.QApplication.translate("Voucher", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.removeButton.setText(QtGui.QApplication.translate("Voucher", "Remove Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setText(QtGui.QApplication.translate("Voucher", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.importButton.setText(QtGui.QApplication.translate("Voucher", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.saveTableButton.setText(QtGui.QApplication.translate("Voucher", "Save Table", None, QtGui.QApplication.UnicodeUTF8))
        self.totalAmountLabel.setText(QtGui.QApplication.translate("Voucher", "Total Amount", None, QtGui.QApplication.UnicodeUTF8))

from _widgets.header import Header
from _views.voucherTableView import VoucherTableView
